### PR TITLE
Fall back to old login flow on GS as this is not yet ready

### PR DESCRIPTION
**Pull request by rullzer**
Probably we also have to do this check in the reauth part of the code?

### CODE REVIEW

**Comment by misch7** [comment]
Looks good to me so far, I'll have a look at the re-auth part.

**Comment by rullzer** [comment]
@misch7 the code in question is at https://github.com/nextcloud/desktop/blob/master/src/gui/creds/webflowcredentials.cpp#L149-L171 I think

Because right now that will just fall back and we need to add a similar query there.

**Comment by misch7** [comment]
🍒 Cherry-picked to stable-2.6

**Pull request merged**
