### PR TITLE
Set default maxChunkSize to 1000MB

### LINKED ISSUE #3313: Set default maxChunkSize to 1000MB
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
The default chunk size of 100MB for the uploads is too less in the current time. Please consider to change it to 1000MB.

**Describe the solution you'd like**
By changing the default value of the max_chunk_size to 1000MB, I was able to tremendously improve the upload speed for big files using the sync client

**Describe alternatives you've considered**
Maybe change it to 10000MB but thats probably already too much.

**Additional context**
I talk about this value: https://docs.nextcloud.com/desktop/3.2/advancedusage.html?highlight=chunk#:~:text=maxchunksize

### PR DESCRIPTION
**Pull request by szaimen**
fix #3313
Signed-off-by: szaimen <szaimen@e.mail.de>

### CODE REVIEW

**Review by mgallien — APPROVED** [review]
I believe that should be fine but what is the reason to do that ?
Can you clarify the reason in the commit message ?
This will not solve the timeout when server is concatenating the chunks into a single file

**Comment by allexzander** [comment]
@szaimen Nice. What was the reason for increasing it? Did this improve the upload speed of large files? Could you kindly resolve conflicts manually and rebase against the master branch?

**Review by allexzander — APPROVED** [review]

**Comment by szaimen** [comment]
Superseded by https://github.com/nextcloud/desktop/pull/3600

**Pull request closed without merging**
