### PR TITLE
makes Qt WebEngine optional only on macOS

### PR DESCRIPTION
**Pull request by mgallien**
should avoid distributing broken builds missing out web flow login that
is required by some cusotmers

Signed-off-by: Matthieu Gallien <matthieu.gallien@nextcloud.com>

### CODE REVIEW

**Review by allexzander — APPROVED** [review]

**Comment by allexzander** [comment]
@mgallien I was too quick to approve. It is failing on drone.

**Review by claucambra — COMMENTED** [review]
Besides the CI failures, why are we separating all these package properties instead of just the webengine? I am not sure we are adding anything with the descriptions except making things longer

**Comment by mgallien** [comment]
> Besides the CI failures, why are we separating all these package properties instead of just the webengine? I am not sure we are adding anything with the descriptions except making things longer

The goal is to improve the summary at end of configure time when running `cmake`.
I can also understand your comment.

**Comment by mgallien** [comment]
> > Besides the CI failures, why are we separating all these package properties instead of just the webengine? I am not sure we are adding anything with the descriptions except making things longer
> 
> The goal is to improve the summary at end of configure time when running `cmake`. I can also understand your comment.

@claucambra so do you want changes or do you approve ?

**Review by claucambra — APPROVED** [review]

**Comment by bill-auger** [comment]
does the build strictly require webengine? - the last i remember, it was intentionally made to avoid that a few years ago - there have been multiple discussions and pull requests about this ( #932 #1808 #856 #2204 #3353 ) - there was even a 'no-webengine' branch at one time working toward that goal - why does this keep creeping back in? - did someone leave the barn door open?

**Comment by TimB87** [comment]
On [CRUX](https://crux.nu) I used to make qtwebengine (especially the qt5 version...) optional, [see this commit](https://crux.nu/gitweb/?p=ports/contrib.git;a=commitdiff;h=7fef2d63ac88c10de6cedf0918a38c70667ce5e0)

@mgallien @claucambra Is there any reason why everybody wants to hard depend on that? It's a huge dependency with a lot of pitfalls, it would be great to be able to avoid it. Maybe a flag to optionally disable it?

**Comment by mgallien** [comment]
important features do not work without QtWebEngine (may be required for users to login to a Nextcloud server)
this is the reason to have this mandatory when feasible to build it

**Comment by TimB87** [comment]
a flag to disable qtwebengine requirement would work for me and probably @bill-auger and @sseneca as well, it can still demand it by default. How do you feel about that @mgallien?

**Comment by mgallien** [comment]
> a flag to disable qtwebengine requirement would work for me and probably @bill-auger and @sseneca as well, it can still demand it by default. How do you feel about that @mgallien?

may work
will review a PR for that (especially if you ping me about it)
that means for example loosing access to using an existing provider via this installer feature
image
so getting something like this merged may be a bit more work than just a couple of `cmake` changes

**Comment by TimB87** [comment]
I for one can not provide a complete PR for that..

**Comment by bill-auger** [comment]
as long as the client (without webengine) can be configure for and be
usable with an arbitrary self-hosted instance, that is acceptable for
our user-base

many people prefer lean software, which does only the minimum that it
needs to do, using the minimum of machine resources - optional and
bloated features could/should be plugins, for those who have the
use-case for the extra features

**Comment by mdkcore0** [comment]
this also [breaks building on some targeted architectures on void-linux](https://github.com/void-linux/void-packages/pull/42361); can we have a flag to disable the use of webengine?

**Pull request merged**
