### PR TITLE
Fix half-translated GUI strings on Windows

### PR DESCRIPTION
**Pull request by claucambra**

### CODE REVIEW

**Comment by mgallien** [comment]
I am testing it.
Before this PR on 3.14.3
image
I included also Kate build on top of Qt6 and ki18n KDE Frameworks 6

**Review by mgallien — CHANGES_REQUESTED** [review]
result with the PR
image
that makes it all in French
seems like something is now worse

**Comment by claucambra** [comment]
> result with the PR image that makes it all in French seems like something is now worse

I have reverted to using QLocale::uiLanguages but, this time, only the first language

Could you try again?

**Review by mgallien — CHANGES_REQUESTED** [review]
@claucambra does not build
can you have a look ?

**Comment by claucambra** [comment]
> @claucambra does not build can you have a look ?

Sorry, pushed too quickly

Fixed it

**Review by mgallien — CHANGES_REQUESTED** [review]
@claucambra still not compiling
you may want to check again

**Pull request merged**
