### PR TITLE
Bugfix/fix upload locked files

### PR DESCRIPTION
**Pull request by mgallien**

### CODE REVIEW

**Comment by mgallien** [comment]
not covering all cases that need a token in case of locks
not having any automated tests

**Review by claucambra — APPROVED** [review]

**Comment by mgallien** [comment]
documentation reference for token locks over WebDAV

https://github.com/nextcloud/3rdparty/blob/b295b1dad9b308faa28b6b21d49d8186856fe48b/sabre/dav/lib/DAV/Locks/Plugin.php#L181-L195
http://www.webdav.org/specs/rfc4918.html#n-example---write-lock-and-copy
http://www.webdav.org/specs/rfc4918.html#opaquelocktoken.lock.token.uri.scheme

**Pull request merged**
