### PR TITLE
Cleaning logs

### PR DESCRIPTION
**Pull request by mgallien**
making logs more useful using logs collected from complex situations
trying to make them less verbose and more targeted toward useful information (i.e. being able to understand sync issues)

### CODE REVIEW

**Review by claucambra — APPROVED** [review]

**Comment by mgallien** [comment]
/backport 6c5c7c27d2a0e69bbf7a7d20b4ef2f00dee7ab78 to stable-3.13

**Comment by mgallien** [comment]
/backport 6c5c7c27d2a0e69bbf7a7d20b4ef2f00dee7ab78 to stable-3.14

**Pull request merged**
