### PR TITLE
Fix build with KF6

### PR DESCRIPTION
**Pull request by nicolasfella**
Set QT_NO_CREATE_VERSIONLESS_FUNCTIONS, otherwise Qt5 and Qt6 conflict

### CODE REVIEW

**Comment by Flowdalic** [comment]
FWIW, a  user reported in https://bugs.gentoo.org/930943#c7 that this fixes the Gentoo build if both Qt 5 and 6 are installed. So this seems to address a real issue that will happen more often once Qt 6 become more common.

**Review by claucambra — APPROVED** [review]

**Review by claucambra — COMMENTED** [review]
Do we not need a qt6_add_resources?

**Comment by mgallien** [comment]
@nicolasfella could you have a try at resolving the conflicts ?
I am trying to really make sure that the CI checks run via github actions are reliable and always green (so except drone and sonarcloud)

**Comment by mgallien** [comment]
@nicolasfella can you rebase on top of master branch ?
I cannot do it because of conflicts

**Comment by Rello** [comment]
Hello,

Thank you for your contribution to the Desktop Client with this pull request.
We are closing this request as it is outdated, no longer relevant (e.g., due to Qt 6), or does not align with the current roadmap.

We truly value your support and hope to see more contributions from you in the future!


Best regards,
Nextcloud Desktop Team

**Pull request closed without merging**
