### PR TITLE
Revert always enable http2

### LINKED ISSUE #7136: Sync error: “Server stopped accepting new streams before this stream was established”
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Nextcloud client has connection losses.

Sync error: “Server stopped accepting new streams before this stream was established”](https://help.nextcloud.com/t/sync-error-server-stopped-accepting-new-streams-before-this-stream-was-established/59209)

### Steps to reproduce

1. Right click on the file
2. Click on Share Options
3. The share dialog does not display the option to share by e-mail
...

### Expected behavior

no connection losses

### Which files are affected by this bug

all

### Operating system

Windows

### Which version of the operating system you are running.

Windows 11

### Package

Official Windows MSI

### Nextcloud Server version

30.0.0

### Nextcloud Desktop Client version

3.14.0

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

_No response_

### Additional info

[log.zip](https://github.com/user-attachments/files/17021027/log.zip)

### PR DESCRIPTION
**Pull request by claucambra**
Should fix #7136 and #7171

### CODE REVIEW

**Comment by mgallien** [comment]
then we will get back issues when people have http1.1 broken and http2 working
we must investigate to figure out what is the problem and only merge this is there is a Qt bug

**Review by mgallien — CHANGES_REQUESTED** [review]
can you change it such that we would have an environment variable to force disable http2 when needed and keep it enable by default ?

**Review by mgallien — APPROVED** [review]
things are broken after this change
we unfortunately have to revert

**Comment by nursoda** [comment]
> AppImage file: [nextcloud-PR-7182-389d6536e593517bb6fddab9789f76cd741edf1b-x86_64.AppImage](https://github.com/nextcloud-desktop-bot/ci-builds/releases/download/PR-7182/nextcloud-PR-7182-389d6536e593517bb6fddab9789f76cd741edf1b-x86_64.AppImage)

WFM (NC 28.0.10 on NGINX 1.27.1/PHP-FPM 8.3.11/MariaDB 11.5.2)

**Comment by hhartz** [comment]
@claucambra FYI, https://bugreports.qt.io/browse/QTBUG-132277

**Comment by hhartz** [comment]
pinging @mgallien as well

**Pull request merged**
