### PR TITLE
Use default member initialization

### PR DESCRIPTION
**Pull request by sbeyer**
This PR introduces default member initialization, a C++
feature available since C++11, in a few locations to
replace the explicit definition of a default constructor.

### CODE REVIEW

**Comment by sbeyer** [comment]
I have seen there were some modernization PRs like using `auto`. I count this PR into the same category. Default member initialization is a good way to get rid of duplication-like code where the default constructor definition only consists of a member initialization list.

Unluckily, C++14 does still not allow default member initialization for bit fields. This would allow to apply this patch to some more structs.

**Comment by jancborchardt** [comment]
Btw @sbeyer we have a Talk conversation for the desktop team where we also invite contributors – would you like to be added with a guest account? :)

**Comment by sbeyer** [comment]
> Btw @sbeyer we have a Talk conversation for the desktop team where we also invite contributors – would you like to be added with a guest account? :)

Yes. (See the private mail I just wrote to you.)

**Pull request merged**
