### PR TITLE
Reinstate Debian build in the new Drone config

### PR DESCRIPTION
**Pull request by ivaradi**
This patch re-adds the Debian build to new Drone config.

### CODE REVIEW

**Comment by ivaradi** [comment]
I am not sure whether the secret keys work, because they are used only when the PR is merged. Otherwise, it seems to work.

**Comment by ivaradi** [comment]
@rullzer, @camilasan Could we move forward with this PR? It's been pending for almost 3 months :)

**Comment by camilasan** [comment]
I believe I wanted @rullzer to look at it.. but sure.

**Comment by camilasan** [comment]
Sorry for the delay @ivaradi

**Pull request merged**
