### PR TITLE
Improve URL input field in Wizard

### PR DESCRIPTION
**Pull request by sbeyer**

### CODE REVIEW

**Comment by sbeyer** [comment]
This is only a change in the look.

The old look:
old

The new look:
new

**Comment by sbeyer** [comment]
Oh, that was quick.

**Comment by jancborchardt** [comment]
Hmm, having only `https://…` there was intentional to keep the technical language to a bare minimum. Am a bit worried that saying "host:port" will confuse more than clarify – but we can see. :)

**Comment by sbeyer** [comment]
> Hmm, having only `https://…` there was intentional to keep the technical language to a bare minimum.

That's why I put it into an extra commit such that I could easily drop it if you don't like the change.

However, I do not think it's too technical language but that it's clearer for people who use a custom port and have no idea how to tell the client to use that port.

**Comment by jancborchardt** [comment]
Yup, no worries. :) "https" is also quite technical, and even "server address" is often an issue. This generally needs some more thinking how to do it best for sure.

**Pull request merged**
