### PR TITLE
Fix expire date field in Share settings

### PR DESCRIPTION
**Pull request by claucambra**
This PR fix several bugs when it comes to properly resetting the expire date field after modification. It also better notifies users when the value they are providing is invalid due to, for instance, a limit of days on the expire date.

Screenshot 2023-05-08 at 20 08 45

### CODE REVIEW

**Comment by claucambra** [comment]
Closes #5627

**Comment by tlueder** [comment]
Hi any updates on this patch?

**Review by allexzander — APPROVED** [review]

**Comment by allexzander** [comment]
@claucambra Please squash commits before merge

**Comment by Spheron101** [comment]
3.9.4 still not working

**Pull request merged**
