### PR TITLE
Issue #705 - Error when connecting to server with self-signed SSL

### PR DESCRIPTION
**Pull request by lavigne958**
### short description
- get the user choice "trust this certificate" (bool) save it in the webengine
- when a certificate error occurs in the webengine, check if user choice override the certificate error

### longer description
when the user agree to use an untrusted certificate, the Account object keep it in a var.
Later on when the WebWiev initialiaze its webEnginePage, it passes the bool value of `trusted` which tells if the user trust or not the server certificate.
then when an error occurs in the webview if the var is at True the error is ignoed.

I thought it might be much safer to pass:
- the boolean value if the user trust the certificate or not
- and the url associated with it
so it can be checked when the error occurs in the webView agains the origin url of the error.

Please add reviewers as I d'ont know any yet.

### CODE REVIEW

**Comment by camilasan** [comment]
What do you think @rullzer? 
Thanks @lavigne958 for proposing a solution :)

**Comment by rullzer** [comment]
Yeah the issue here is that the certificate store we use in general can't be used with the webview.

I would not just pass a boolean but really pass in a url. Or rather try to fire off a request with the network access manager to the url. If it is valid and passes we really trust the certificate.

@lavigne958 ^^ would you like to help implement that?

I think for 2.5.2 I can just add a simple dialog. If the certificate is self signed show a dialog `<url> is using a self signed certificate. Continue?`

Then we can fix it properly later.

**Comment by lavigne958** [comment]
@rullzer I did not get everything you wrote...
I can update the PR and pass the url instead of the boolean. 
But you talked about the NetworkAccessManager and don't this component yet. So I'll have a look at it before saying if I can use it or not.

**Comment by lavigne958** [comment]
Here is a new version comparing hosts between the one from the certificate error that the user trust, and the one from the webview certificate error, if it's the same, it is ok then.

**Comment by DominiqueFuchs** [comment]
@rullzer Whats the current state of this issue - is this still a thing? :star2:

**Pull request closed without merging**
