### PR TITLE
Update command-rebase.yml from template

### PR DESCRIPTION
**Pull request by skjnldsv**
From https://github.com/nextcloud/.github

### CODE REVIEW

**Review by mgallien — APPROVED** [review]
Thanks

**Comment by skjnldsv** [comment]
> /rebase

won't work, need to be in master :)

**Comment by mgallien** [comment]
> > /rebase
> 
> won't work, need to be in master :)

so I did it myself

**Comment by mgallien** [comment]
@skjnldsv You need to fix the commits because we require DCO to be able to merge your work. Please have a look at the hint from the DCO action.

**Comment by skjnldsv** [comment]
@mgallien should be fine for such changes :wink:

**Review by FlexW — APPROVED** [review]

**Review by mgallien — APPROVED** [review]

**Pull request merged**
