### PR TITLE
l10n: Correct text string

### PR DESCRIPTION
**Pull request by Valdnet**
Signed-off-by: Valdnet <47037905+Valdnet@users.noreply.github.com>

### CODE REVIEW

**Review by er-vin — COMMENTED** [review]
Not sure I see the point. Those strings are overwritten during the app lifetime anyway. They can just be ignored.

**Comment by er-vin** [comment]
Clicked send too quickly...

Is it some tooling flagging them somehow? I wonder if that'd be enough to mark them as non translated strings instead. Semantically this would feel more correct then pushing people to translate something which doesn't need to be. :-)

**Comment by Valdnet** [comment]
Well, these strings are in Transifex and translators translate them.

**Comment by er-vin** [comment]
Right, so the right fix would be instead to mark them as non-translated strings in Qt Designer, this way they'll stop being extracted. No need to drop useless strings on the translators.

**Comment by FlexW** [comment]
@er-vin The strings are not marked as translatable at the moment.

**Comment by er-vin** [comment]
> @er-vin The strings are not marked as translatable at the moment.

Oh right! They got the `notr`... something is wrong if they get extracted 
then.

**Comment by Valdnet** [comment]
In this case, I am closing PR, but I hope that the problem will be discussed until the end 😉.

**Comment by FlexW** [comment]
@Valdnet I created an issue for that https://github.com/nextcloud/desktop/issues/3221

**Pull request closed without merging**
