### PR TITLE
Always build with updater. Use 'beta/stable' channel selector in 'General Settins' dialog with default 'stable'.

### PR DESCRIPTION
**Pull request by allexzander**
Signed-off-by: alex-z <blackslayer4@gmail.com>

image
This will fix https://github.com/nextcloud/desktop/issues/3636

### CODE REVIEW

**Review by claucambra — APPROVED** [review]

**Comment by allexzander** [comment]
> Can you add a screenshot? :-)

Added. See the bottom part of the dialog. The selector will now always be visible unless **BUILD_UPDATER** is set to `OFF` during the build.

**Comment by tobiasKaminsky** [comment]
Works as expected, correct updater query 👍

**Review by tobiasKaminsky — APPROVED** [review]

**Review by mgallien — APPROVED** [review]

**Comment by tobiasKaminsky** [comment]
I updated https://github.com/nextcloud/desktop/issues/2600 to have this reflected.

**Comment by claell** [comment]
I guess this explains why I have been on 3.4.4 without any update notifications at all in the meantime?

**Pull request merged**
