### PR TITLE
Use dav instead of webdav

### LINKED ISSUE #3342: Use only remote.php/dav instead of remote.php/webdav
https://github.com/nextcloud/server/issues/25867

### PR DESCRIPTION
**Pull request by FlexW**
Fixes #3342

Signed-off-by: Felix Weilbach <felix.weilbach@nextcloud.com>

### CODE REVIEW

**Review by allexzander — APPROVED** [review]

**Review by mgallien — APPROVED** [review]
You have used a tool to do the replacement everywhere ?

**Comment by FlexW** [comment]
> You have used a tool to do the replacement everywhere ?

yep. I used `sed`.

**Comment by allexzander** [comment]
> > You have used a tool to do the replacement everywhere ?
> 
> yep. I used `sed`.

magic! XD

**Pull request merged**
