### PR TITLE
Fixing memory leaks in the encryption module

### PR DESCRIPTION
**Pull request by ivan-cukic**
Due to usage of early-returns, combined with malloc/free,
several buffers that get allocated are leaked when an error
occurs.

Several functions had potential leaks:

 - `encryptStringSymmetric` leaked `ctext`
 - `EncryptionHelper::fileDecryption` leaked `out`
 - `EncryptionHelper::fileEncryption` leaked `out`

Most of the functions had leaks of the cypher context.

This patch uses `QByteArray` as the handler for the dynamically
allocated buffers for openssl to operate on. This also removes
the need for conversions from malloc'd buffers to `QByteArray`
variables previously present in the code.

It also introduces a `CypherCtx` thin wrapper class to provide
a leak-free handling of `EVP_CIPHER_CTX`.

### CODE REVIEW

**Comment by ivan-cukic** [comment]
This is a WIP, there are a few more classes of leaks that can be fixed.  I'll wait for comments on whether this approach is acceptable to NC maintainers before continuing.

**Comment by camilasan** [comment]
I like where this is going. Please, continue :)

**Comment by ivan-cukic** [comment]
Added RAII classes for other OpenSSL resources used.

Since `X509_REQ` is used only in one place, instead of creating a class for it, it is cleaned up using `qScopeGuard`.

**Comment by DominiqueFuchs** [comment]
Hey @ivan-cukic I finally found the time to resolve the merge conflicts - thanks for the memory maintenance here! I had to introduce a fallback clause for the use of QScopeGuard as this was only introduced with Qt 5.12:
https://github.com/nextcloud/desktop/blob/99dac294e90a4a51c861126b3ae521c9f7bef93a/src/libsync/clientsideencryption.cpp#L1006-L1014

The _else_ case now resembles the old way without cleanup management. Do you want to add anything on this?

**Pull request merged**
