### PR TITLE
Add photothumb.db to sync-exclude.lst

### PR DESCRIPTION
**Pull request by nicrame**
Add photothumb.db file that is thumbnails generated by Photoscape application (generated in every folder with graphic files).

### CODE REVIEW

**Comment by nicrame** [comment]
> 
> 
> Hi @nicrame,
> 
> seems fine for me, thanks for your contribution! :)
> 
> Could you please sign off your commit to satisfy our CI's DCO check?
> See here: https://github.com/nextcloud/desktop/runs/770414663
> 
> Thanks!

How can i do that? I'm using github web gui, i didn't touch console/terminal.

**Comment by misch7** [comment]
> How can i do that? I'm using github web gui, i didn't touch console/terminal.

Ah okay, I've no idea how to do this using the Web GUI, I'm only on the terminal ;-)

Basically you'd just have to modify the commit message and add a line like this:

`Signed-off-by: Your Name <your@mail.tld>`

Is there an option to modify the commit message via GUI?

**Comment by misch7** [comment]
> Signed-off-by: Marcin Wilk [...]

Seems like that didn't work. However, next time just add it below your commit's message and then our CI should be happy. For now I'll cheat and set it to pass so we can merge it ;-)

**Comment by misch7** [comment]
Merged, closing #2092.

**Comment by misch7** [comment]
🍒 Cherry-picked to stable-2.6

**Pull request merged**
