### PR TITLE
delete PNGs that are not used anywhere

### PR DESCRIPTION
**Pull request by rubo77**
Those files are a total of 1,2MB.

It seems like those files are not used in the code anywhere, so we can safely delete them

checked with each filename (without path) via

    while read f; do grep "$f" * -Rq; done

see #2087

### CODE REVIEW

**Comment by sbeyer** [comment]
Citation from #2087 discussion:
> the twitter, facebok and co images could be used somehow with a generated name from the service, I didn't search for that

Only the SVGs are used. It seems a7e1003c4117c3e07ef7db8ac05095974db45066 created SVGs and PNGs but the PNGs are never used...

**Comment by rubo77** [comment]
I reinstated the sidebar_icon_osx_18.png  and the oC_* files, this narrows it down to 

```
doc/_shared_assets/static/logo-blue.png
doc/_shared_assets/static/social/diasporaround.png
doc/_shared_assets/static/social/facebook.png
doc/_shared_assets/static/social/googleplus.png
doc/_shared_assets/static/social/mail.png
doc/_shared_assets/static/social/rss.png
doc/_shared_assets/static/social/twitterround.png
doc/_shared_assets/themes/nextcloud_com/static/img/social/diasporaround.png
doc/_shared_assets/themes/nextcloud_com/static/img/social/facebook.png
doc/_shared_assets/themes/nextcloud_com/static/img/social/googleplus.png
doc/_shared_assets/themes/nextcloud_com/static/img/social/rss.png
doc/_shared_assets/themes/nextcloud_com/static/img/social/twitter.png
doc/_shared_assets/themes/nextcloud_com/static/img/social/twitterround.png
doc/_shared_assets/themes/nextcloud_release/static/img/social/diasporaround.png
doc/_shared_assets/themes/nextcloud_release/static/img/social/facebook.png
doc/_shared_assets/themes/nextcloud_release/static/img/social/googleplus.png
doc/_shared_assets/themes/nextcloud_release/static/img/social/rss.png
doc/_shared_assets/themes/nextcloud_release/static/img/social/twitter.png
doc/_shared_assets/themes/nextcloud_release/static/img/social/twitterround.png
doc/images/wizard_overview.png
doc/images/wizard_targetfolder.png
doc/images/wizard_url.png
doc/images/wizard_user.png
theme/colored/128-Nextcloud-sidebar.png
theme/colored/256-Nextcloud-sidebar.png
```

**Comment by sbeyer** [comment]
> I reinstated the sidebar_icon_osx_18.png

Have you found code that uses it?

>```
> 4,0K    theme/colored/128-Nextcloud-sidebar.png
> 8,0K    theme/colored/256-Nextcloud-sidebar.png
> ```

Why are these still deleted? (See my comment above.)

**Comment by rubo77** [comment]
I thought the code you linked to referred to the PNG with the numbers at the end

**Comment by FlexW** [comment]
@rubo77 Are you still interested in this pr?

**Comment by rubo77** [comment]
Sorry, I have no time for it

**Comment by FlexW** [comment]
Okay, I will then close this pr. If you want to work again on it, we can reopen it.

**Pull request closed without merging**
