### PR TITLE
docs: Replace "preceded" with "followed"

### PR DESCRIPTION
**Pull request by carlcsaposs**
Signed-off-by: Carl Csaposs <carl@csaposs.com>

### CODE REVIEW

**Review by claucambra — APPROVED** [review]

**Review by tflidd — APPROVED** [review]

**Comment by mgallien** [comment]
@carlcsaposs thanks for your contribution
once we reach a state where this PR can be merged we will wait a bit more due to the preparation of the next feature release

**Comment by carlcsaposs** [comment]
@camilasan Should I rebase this PR now or leave it for someone with write access to rebase once it's ready to be merged?

**Comment by mgallien** [comment]
> @camilasan Should I rebase this PR now or leave it for someone with write access to rebase once it's ready to be merged?

apparently I eventually figured out how to rebase incoming PR directly from within github
will take care of integrating this

thanks for the contribution

**Pull request merged**
