### PR TITLE
Added conditionals around non-macOS packages

### PR DESCRIPTION
**Pull request by elsiehupp**
As discussed in https://github.com/nextcloud/desktop/issues/2893, this just keeps CMake from throwing warnings on macOS for packages that can't be installed on macOS.

### CODE REVIEW

**Comment by FlexW** [comment]
This has been already done here https://github.com/nextcloud/desktop/pull/2886

**Comment by elsiehupp** [comment]
@FlexW yes, I know you did it, but that request hasn't been merged, and I'm feeling impatient. Basically I don't want the changes to the documentation to be merged before the inapplicable warnings are suppressed, but I also want to merge the changes to the documentation sooner rather than later, hence why I did an extremely target pull request.

**Comment by FlexW** [comment]
> @FlexW yes, I know you did it, but that request hasn't been merged, and I'm feeling impatient. Basically I don't want the changes to the documentation to be merged before the inapplicable warnings are suppressed, but I also want to merge the changes to the documentation sooner rather than later, hence why I did an extremely target pull request.

I can understand you but if this pr would be merged then the other pr needs to be changed and changing the CMake scripts is a little bit dangerous and therefore needs some coordination as you can see from the comments in the pr ;)

**Comment by elsiehupp** [comment]
Okay! I took a look at your PR. What else should I do in order to help that proceed? (I can add an approval from my side, but I don't want to do that prematurely.)

**Pull request closed without merging**
