### PR TITLE
Add support for compiling without QtWebEngine (webflow / flow2 support)

### LINKED ISSUE #932: Build without qt-webengine
Hello,

Thank you very much for your efforts on providing such a good cloud application. 

I saw that the nextcloud client depends on qt-webengine. As this software is 
[considered to be nonfree](https://lists.gnu.org/archive/html/directory-discuss/2017-11/msg00014.html) the hole client cannot be free. For a more informations about free software see [fsf.org](https://www.fsf.org/about/what-is-free-software).

I would kindly ask you how I can  build the client without qt-webengine?

Furthermore: Do the [daily images](https://download.nextcloud.com/desktop/daily/Linux/) contain the nonfree parts with qt-webengine?

(OS: [Parabola GNU/Linux-libre](parabola.nu))

### PR DESCRIPTION
**Pull request by sroracle**
Fixes #932. I opted to make it default to Basic authentication in the absence of WebEngine but maybe it could be OAuth as well (maybe I can make that configurable too?)

### CODE REVIEW

**Comment by theova** [comment]
Are there any updates on this? I would love to see this merged.

**Comment by sroracle** [comment]
Need to rebase it yet again, and I'm not really interested in doing so until I either need to bump the package in my distro or the devs show any interest in merging this.

**Comment by theova** [comment]
I have rebased it and successfully built it without webengine. See #2204 .

**Comment by sroracle** [comment]
Superseded by #2204

**Pull request closed without merging**
