### PR TITLE
Show more informative error message when VFS hydration fails. Displaya popup and put an error into activity list. More detailed logs.

### PR DESCRIPTION
**Pull request by allexzander**
image

For https://github.com/nextcloud/desktop/issues/6132

### CODE REVIEW

**Review by claucambra — APPROVED** [review]

**Comment by allexzander** [comment]
@jancborchardt @nimishavijay 
We need a way to provide error details when VFS files download files due to server error but it is not visible to the user what caused it.
I came up with an idea to show a popup and add an activity to the list.
Any ideas on how to improve it? Or is it OK this way already?

**Comment by nimishavijay** [comment]
If I see this error are there any steps I can take to fix it? (change some settings, check network connection, etc). We can simplify the error message to something like

```
Error downloading [filename]
[Filename] could not be downloaded. Please [action] and try again.

                              [Cancel button] [Try again button]
```

**Comment by allexzander** [comment]
> If I see this error are there any steps I can take to fix it? (change some settings, check network connection, etc). We can simplify the error message to something like
> 
> ```
> Error downloading [filename]
> [Filename] could not be downloaded. Please [action] and try again.
> 
>                               [Cancel button] [Try again button]
> ```

@nimishavijay No, the whole reason for this popup is for user to make a screenshot and let developers know about the exact issue. The problem is, when user has an issue with VFS like the one on the screenshot, it is a server side problem but it is being treated by a desktop client but from user’s perspective. Then user creates a bug report and quite often forgets to attach logs. Then in 24 hours logs are rotated and we can no longer tell what happened, which error came from server. Then it is impossible to investigate in case of random errors on the server. And we are receiving such a ticket but with just a screenshot and no logs or something. With this pop up we will see on a screenshot if this was a server issue (only then popup will show up) and then ask server engineers to investigate. Otherwise we already have a system popup from Windows VFS but it does not provide any details to what happened and if it was a server issue or not.

**Comment by nimishavijay** [comment]
Ah okay understood, in that case we could show it under a "More details" section. Showing a technical error up front would be confusing to non-technical users, who are the majority.  We could do something like this:

```
Error downloading [filename]
[Filename] could not be downloaded.
> More details

[Cancel button] [Try again button]
```

On clicking "More details" the detailed info with the error code will be shown

In the tray menu also could we show a [More info] button which then exposes the error codes? So something like `Error downloading file [More details]` and clicking on "More details" would show the error message below. What do you think? :)

**Comment by allexzander** [comment]
> Ah okay understood, in that case we could show it under a "More details" section. Showing a technical error up front would be confusing to non-technical users, who are the majority. We could do something like this:
> 
> ```
> Error downloading [filename]
> [Filename] could not be downloaded.
> > More details
> 
> [Cancel button] [Try again button]
> ```
> 
> On clicking "More details" the detailed info with the error code will be shown
> 
> In the tray menu also could we show a [More info] button which then exposes the error codes? So something like `Error downloading file [More details]` and clicking on "More details" would show the error message below. What do you think? :)

**Review by nimishavijay — APPROVED** [review]
Nice! Looks good :)

**Pull request merged**
