### PR TITLE
Add screenshots of the latest features.

### PR DESCRIPTION
**Pull request by camilasan**
I want feedback about the text changes and menu order change in our docs:
https://docs.nextcloud.com/desktop/3.4/ (current one)

See screenshots for the changes:

As per marketing request:
Menu order:
menu

Sync state:
sync-state

User Status:
userstatus

Activities list:
activities-list

Unified search and share dialog:
unified-search

The screenshots do not look the same as in the public link because I am running the docs locally.

### CODE REVIEW

**Review by mgallien — APPROVED** [review]
thanks

**Comment by camilasan** [comment]
I am still trying to improve the text and screenshots.

**Comment by camilasan** [comment]
As per marketing request:
Menu order:
menu

Sync state:
sync-state

User Status:
userstatus

Activities list:
activities-list

Unified search and share dialog:
unified-search

**Comment by jospoortvliet** [comment]
Some feedback.
> Sync state:
> if there are synchronization issues they will show up here.
It would be good to give a hint or two about what to do. Or, if there is documentation about that, link to it. Maybe you can just click the item? I'm not sure what that does, probably depends on the problem, but explaining the types of problems and what to do with them would probably help a lot of users.

If you want I can help here - if you explain in 'nerd' then I can write it in a nice text and you can put that in the PR ;-)

The rest looks good, can't think of much to add.

**Comment by camilasan** [comment]
Update:

sync-issues
user-status-text

**Review by jospoortvliet — APPROVED** [review]
Great!

**Review by claucambra — APPROVED** [review]

**Pull request merged**
