### PR TITLE
Improve drone config

### PR DESCRIPTION
**Pull request by er-vin**
This depends on nextcloud/docker-ci#234 to be in and tagged first.

### CODE REVIEW

**Comment by sbeyer** [comment]
I'll do the review when the CI passes, but in general it looks very good (despite the many c&p'ed volume and image fields... can those be declared globally?)

**Comment by er-vin** [comment]
> I'll do the review when the CI passes, 

Yeah we need the other PR in first.

> but in general it looks very good (despite the many c&p'ed volume and image fields... can those be declared globally?)

Not that I know of, but I got some more plan for that stuff later on which should get rid of the duplication in another PR.

**Comment by er-vin** [comment]
Yay finally! Slightly underwhelmed that I'll have to work on a separate image for the appimage build, oh well...

**Pull request merged**
