### PR TITLE
add bash script to share file/dir using public link

### PR DESCRIPTION
**Pull request by jose1711**

### CODE REVIEW

**Comment by camilasan** [comment]
Hi @jose1711 Thanks for the PR, could you elaborate on your motivation for writing this script? :)

**Comment by jose1711** [comment]
Sure. Long story short I am a command-line addict and I spend most of the time in the terminal window even when running X11. As I was missing an option to quickly share a file without a need to go to browser window or running nautilus I explored the option I have to do the same in bash. Now I can quickly share a file via a command menu in midnight commander or directly from a shell session. Maybe someone will find this useful too and/or improve it further. Btw Dropbox for instance offers a similar command line API (`dropbox-cli`).

**Comment by FlexW** [comment]
We have the `nextcloudcmd` command. Maybe the functionality could be added in there? (I'm not sure about it).

**Review by mgallien — CHANGES_REQUESTED** [review]
This can be interesting but this current script is really specific to your use case.

Could you please see if you have provide something more generic that would not rely on the nextcloud desktop client running and putting something in the clipboard ?

This script while working is not something that would be easy to use because except reading it, you would not know what happen when executing it. I needed to carefully read the code to understand the way one can use it.

That could imply working on a tool called `nextcloudshare` (could be done via bash) that would expose share feature to command line. It would be better if you implement it in a cross platform language given we have users on Linux desktops, Mac OS X and Windows.

**Comment by mgallien** [comment]
I also forgot to ask to take care of the DCO failed check. This is important as we are not allowed to accept contributions without it.

**Comment by Rello** [comment]
Hello,

Thank you for your contribution to the Desktop Client with this pull request.
We are closing this request as it is outdated, no longer relevant (e.g., due to Qt 6), or does not align with the current roadmap.

We truly value your support and hope to see more contributions from you in the future!


Best regards,
Nextcloud Desktop Team

**Pull request closed without merging**
