### PR TITLE
l10n: Unify spelling

### PR DESCRIPTION
**Pull request by Valdnet**
Spelling unification in Nextcloud applications.

### CODE REVIEW

**Review by rakekniven — APPROVED** [review]

**Comment by FlexW** [comment]
Thanks @Valdnet. It it possible that you squash your commits before we merge that?

**Comment by Valdnet** [comment]
@FlexW I think you can merge 😉.

**Review by er-vin — COMMENTED** [review]
This needs a rebase and squashing all the commits. Someone from the team could do this manually and force push in the branch.

**Comment by FlexW** [comment]
@Valdnet I squashed and rebased. To please the DCO bot next time, please add `--signoff` to the commit command, like `git commit --signoff -m "Your commit message"`. You can find more information about that flag [here](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff)

**Pull request merged**
