### PR TITLE
Build appimage with libcloudproviders support

### PR DESCRIPTION
**Pull request by juliushaertl**
- [ ] Add meson/ninja to ci docker container
- [ ] Check if we can build with available meson/ninja versions

```
Meson version is 0.29.0 but project requires >=0.40.0.
```

### CODE REVIEW

**Comment by rullzer** [comment]
You need to rebase your code :P

**Comment by mgallien** [comment]
@juliushaertl do you still plan to work on that ?

**Comment by juliushaertl** [comment]
I fear I won't have time to look into this again anytime soon, I guess we close this for now then. Anyone can of course pick up :)

**Pull request closed without merging**
