### PR TITLE
l10n: Replace apostrophe with double quotation

### PR DESCRIPTION
**Pull request by Valdnet**
Issue: #3278.

Signed-off-by: Valdnet <47037905+Valdnet@users.noreply.github.com>

### CODE REVIEW

**Comment by rakekniven** [comment]
> @rakekniven We usually rebase instead of merging master to update the pull request :) Unfortunate this is not possible from the web ui and "Update this pull request" does the wrong thing.

Then I am lost 😩. Can you disable the update button. 
Using the web interface to update for many other repos before.

**Comment by FlexW** [comment]
> > @rakekniven We usually rebase instead of merging master to update the pull request :) Unfortunate this is not possible from the web ui and "Update this pull request" does the wrong thing.
> 
> Then I am lost . Can you disable the update button.
> Using the web interface to update for many other repos before.

I know this is confusing. But "Update branch" create a unnecessary merge commit. Unfortunately, it is not possible to disable that button without enforcing up to date pull requests.

**Comment by Valdnet** [comment]
@FlexW and @rakekniven Please approval :grin:.

**Review by rakekniven — APPROVED** [review]

**Comment by FlexW** [comment]
@Valdnet The problem is this pr broke a lot of unit tests. It's quite some work to bring them back.

**Comment by Valdnet** [comment]
> It's quite some work to bring them back.

@FlexW What should be done. Is there any rule to fix the test?

**Comment by FlexW** [comment]
@Valdnet On need to check why the test fails and then correct it.

**Comment by Valdnet** [comment]
@FlexW Hmmm… My guess is that I will need a compiler for this test? It is probably not possible to perform a test from the GitHub level?

**Comment by FlexW** [comment]
@Valdnet In theory you could fix this from the webui, but it will be tedious and time-consuming.

**Comment by Valdnet** [comment]
@FlexW Thanks for the answer. So the work was in vain 😬.

**Comment by mgallien** [comment]
@Valdnet is it possible for you to rebase and merge this on the latest commit from master branch ?
there is a conflict within `src/common/checksums.cpp`

**Comment by Valdnet** [comment]
@mgallien Hmmm… What exactly would I have to do?

**Comment by Valdnet** [comment]
@mgallien Hmmm… I did a rebase. Corrected the `src/common/checksums.cpp` file to remove the conflict and probably to no avail. Am I doing something wrong?

**Comment by Valdnet** [comment]
@mgallien @FlexW Please merge 😉.

**Comment by allexzander** [comment]
@Valdnet I am not sure how to commit changes to this PR. Can you create a branch out of master via GIT Cmd:
`git checkout -b "bugfix/Valdnet-patch-5"`, and then, move your replacements there? I can fix tests, but, I am failing to understand how this branch was created.

**Comment by Valdnet** [comment]
I decided to re-introduce the changes and reissue the PR #3604. Please approval.

**Pull request closed without merging**
