### PR TITLE
Modernize the Dolphin action plugin

### PR DESCRIPTION
**Pull request by ivaradi**
Instead of installing a .desktop file, it is now converted to JSON and compiled into the plugin itself. The plugin is also installed into a different directory.

As described in #4425, Dolphin complains about the .desktop file indicating that is an outdated solution. This PR moves the plugin to the recommended JSON-based solution.

### CODE REVIEW

**Review by claucambra — APPROVED** [review]
Thanks! :)

**Comment by claucambra** [comment]
> I think the SonarCloud analysis does not fail because of the patch, or am I missing something? What can be done to get the PR merged? @claucambra could you help with this?

Seems like SonarCloud is failing for some other reason, unrelated to your changes

**Comment by mgallien** [comment]
> I think the SonarCloud analysis does not fail because of the patch, or am I missing something? What can be done to get the PR merged? @claucambra could you help with this?

this is due to the token being a private secret only available for jobs from branch of the main repository and not clone
never had time to dig into this to see if there is a solution

**Pull request merged**
