### PR TITLE
Happy new year

### PR DESCRIPTION
**Pull request by ChristophWurst**
Just noticed that our current client shows -2018. Figured we could update this.

### CODE REVIEW

**Comment by misch7** [comment]
🍒 Cherry-picked to stable-2.6

**Comment by ChristophWurst** [comment]
> The backport to stable-2.6 failed. Please do this backport manually.

lol, the change wasn't *that* complicated :)

thanks @misch7!

**Comment by misch7** [comment]
> lol, the change wasn't _that_ complicated :)

Like in real life: A lot of bureaucracy for small things - and even then the bot complains 🙈

> thanks @misch7!

You're welcome @ChristophWurst! Thanks for looking at the little details ;)

**Pull request merged**
