### PR TITLE
Redesign local folder information in the account-adding wizard

### PR DESCRIPTION
**Pull request by claucambra**
Addresses point 3 of #4052

Screenshot 2022-06-16 at 15 15 06

Signed-off-by: Claudio Cambra <claudio.cambra@gmail.com>

### CODE REVIEW

**Review by mgallien — APPROVED** [review]

**Comment by nimishavijay** [comment]
Looks good! :) I'm also thinking if the path is more than 4 levels long we could show only the first and last folders and ellipsise in the middle?

**Comment by claucambra** [comment]
> Looks good! :) I'm also thinking if the path is more than 4 levels long we could show only the first and last folders and ellipsise in the middle?

This is possible but difficult to do properly when it comes to a flexible layout, or window resizing, as `QPushButton` does not properly support things such as eliding on width changing :(

Would it be a better idea to display the folder path as a label, as we do with the remote location, and then have the button explicitly say "Change local folder" or something along those lines?

**Comment by nimishavijay** [comment]
Ah okay okay, then your solution makes sense :)
We could say "Choose another folder" or "Choose a different folder" or just "Choose folder" cc @jancborchardt on the wording here. If we are just using labels then can we ellipsise?

Also unrelated detail but we should middle align the 3 big icons (the avatar icon, the arrow, and the folder icon) if possible :)

**Comment by claucambra** [comment]
> Ah okay okay, then your solution makes sense :) We could say "Choose another folder" or "Choose a different folder" or just "Choose folder" cc @jancborchardt on the wording here. If we are just using labels then can we ellipsise?

Labels can be elided, no problem!

> Also unrelated detail but we should middle align the 3 big icons (the avatar icon, the arrow, and the folder icon) if possible :)

Sure, I will align them

**Comment by claucambra** [comment]
> 👍 on the middle-aligning of the avatar, arrow and folder icon. Username and "Local folder" text should be at the same height.
> 
> Also, the avatar is huge, can you reduce the size of it to match the folder icon? :)
> 
> And yep, we can do:
> 
> > **Local folder**
> > Documents / Nextcloud (6 GB free space) [subline style, in grey]
> > Choose different folder [button]

@jancborchardt  @nimishavijay 
Turned out to not be as easy as expect
ed, but here is a screenshot:

Screenshot 2022-06-16 at 15 15 06

I moved the free space data to its own line as I felt in 99% of cases, the path text was too long to put the free space data alongside it, and it would elide the path too much to be useful

**Review by nimishavijay — APPROVED** [review]
Looks amazing now! Super nice :) 🚀

**Review by jancborchardt — APPROVED** [review]
Nice work! :)

**Pull request merged**
