### PR TITLE
l10n: Delete space and capital letter

### PR DESCRIPTION
**Pull request by Valdnet**
Signed-off-by: Valdnet <47037905+Valdnet@users.noreply.github.com>

### CODE REVIEW

**Comment by FlexW** [comment]
@Valdnet could you squash the commits? That we get just one single commit instead of seven? If you don't know how to do it, I will do it for you.

**Comment by Valdnet** [comment]
> If you don't know how to do it, I will do it for you.

@FlexW I do not know. Can I ask you for it 😉.

**Comment by camilasan** [comment]
> I do not know. Can I ask you for it wink.

https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History - see "Changing Multiple Commit Messages"

> EDIT: I don't think I'm authorized to do that.

Yes, you are :)

**Comment by Valdnet** [comment]
> https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History - see "Changing Multiple Commit Messages"

Is it possible from GitHub?

**Comment by FlexW** [comment]
@Valdnet I will do it for you. No, I don't think it's possible from GitHub. You need to install git on your computer for that. Maybe you want to invest some time in the future to install git on your computer and make your commits/pull requests from there :) It's not complicated.

**Comment by Valdnet** [comment]
> I will do it for you.

@FlexW Thanks 😉.

> Maybe you want to invest some time in the future to install git on your computer and make your commits/pull requests from there :) It's not complicated.

I work on different computers and it would be less convenient. It's more accessible for me to make changes via GitHub.

> You need to install git on your computer for that.

I only have it installed on my personal computer.

**Review by FlexW — APPROVED** [review]

**Pull request merged**
