### PR TITLE
Fix share dialog

### PR DESCRIPTION
**Pull request by camilasan**
### From issue https://github.com/nextcloud/desktop/issues/158

There is some code commented out and TODO's that I believe we could deal with later.

### Known issues
- Share link: Allow editing in files is a radio button - it needs to become a check box.
- Share link: It needs two clicks on the tool button for it to show up.
- Share link: only unchecking enabled deletes the link correctly, but if you use the Unshare action in the menu, it tries to delete it twice.
- What is the "ShareDialogStartPage"?

share-v2-final-4
share-v2-final
sare-v2-final-2
share-v2-final-3

### CODE REVIEW

**Comment by camilasan** [comment]
@jancborchardt ^^

**Comment by jancborchardt** [comment]
Just copying over what we talked about on Signal already :)

- [ ] "can share" should be in the 3-dot menu
- [ ] as should be delete/unshare
- [ ] and then at some point the name needs to be ellipsized

**Comment by jancborchardt** [comment]
And here’s a screenshot of how it’s for Share links in the web interface (icons missing though because of current bug ;)
screenshot from 2018-07-24 21-50-37

**Comment by camilasan** [comment]
Status:
new-share-dialog-link-options-pwd
new-share-dialog-link-options-expiration

**Comment by jancborchardt** [comment]
Can "Copy link" and "Unshare" get icons? Or at least not have a checkbox? Otherwise it looks a bit strange and like a very long list. :)

The icons are icon-clippy and icon-delete from core/img/actions: https://docs.nextcloud.com/server/14/developer_manual/design/icons.html

**Comment by camilasan** [comment]
Almost...
share-v2
share-v2-actions-with-icons

**Comment by rullzer** [comment]
CI was acting up. But is green in https://github.com/nextcloud/desktop/pull/528

**Comment by MorrisJobke** [comment]
@camilasan This is so nice! 👍 Looks awesome :)

**Pull request merged**
