### PR TITLE
Update screenshot in README.md

### PR DESCRIPTION
**Pull request by FlexW**

### CODE REVIEW

**Review by allexzander — APPROVED** [review]

**Comment by splitt3r** [comment]
Long overdue 😬 maybe move the tray icon (monochrome one) to the visible tray area?

**Comment by FlexW** [comment]
@splitt3r Good idea. Was not aware that you can move the tray icons around :) Thanks. How do you like it now?

**Comment by splitt3r** [comment]
> 
> 
> @splitt3r Good idea. Was not aware that you can move the tray icons around :) Thanks. How do you like it now?
> 
> EDIT: I think we should use the coloured one, as this is the default one.

I'm fine with that 👍🏻 looks great now.

**Review by mgallien — APPROVED** [review]
thanks

**Review by splitt3r — APPROVED** [review]

**Pull request merged**
