### PR TITLE
remove theme.qrc as it will be generated during build

### PR DESCRIPTION
**Pull request by Dimon4eg**
And theme.qrc is even already ignored in .gitignore

### CODE REVIEW

**Comment by FlexW** [comment]
Thank you. That one is on the ignore list. It seems like it was never removed.

**Review by FlexW — APPROVED** [review]

**Review by mgallien — APPROVED** [review]
@Dimon4eg Would like to help us cleaning our mess such that we no longer generate files in the source tree ?

**Comment by Dimon4eg** [comment]
@Dimon4eg will try when will have free time

**Comment by FlexW** [comment]
\rebase

**Pull request merged**
