### PR TITLE
Create symlinks for the small-letter application icon file names

### PR DESCRIPTION
**Pull request by ivaradi**
The application icon file's name is ```Nextcloud.png``` with a capital ```N```. However, the ```mirall.desktop.in``` file refers to the icon as ```@APPLICATION_EXECUTABLE@```, which is substituted by ```nextcloud``` (small ```n```) in the ```.desktop``` file. This way the GNOME Shell does not find the application icon on Ubuntu and displays some default image.

This fix modifies the build procedure to create symlinks with a small ```n```. 

However, I am wondering if this is the right way to solve this issue. Shouldn't the ```mirall.desktop.in``` file be modified instead to refer to, e.g. ```@APPLICATION_NAME@```? How does it work on other systems? Or is this file used only by Ubuntu?

This pull request attempts to partly solve #583.

### CODE REVIEW

**Comment by camilasan** [comment]
> However, I am wondering if this is the right way to solve this issue. Shouldn't the mirall.desktop.in file be modified instead to refer to, e.g. @APPLICATION_NAME@? How does it work on other systems? Or is this file used only by Ubuntu?

Does anyone know? @juliushaertl  @rullzer ? 

I would say: let's merge it and if we find a better solution later... we can always improve it.

**Comment by juliushaertl** [comment]
The desktop file should actually just use `APPLICATION_ICON_NAME` from https://github.com/nextcloud/desktop/blob/master/NEXTCLOUD.cmake#L7 

But I'm not sure if we maybe already have some custom cmake rules, that make this work on othre platforms.

**Comment by ivaradi** [comment]
Shall I then modify ```mirall.desktop.in``` to use ```APPLICATION_ICON_NAME``` and see what happens (especially on other systems)? It probably does not hurt...

**Comment by camilasan** [comment]
> Shall I then modify mirall.desktop.in to use APPLICATION_ICON_NAME and see what happens (especially on other systems)? It probably does not hurt...
Yes, please @ivaradi

**Pull request merged**
