### PR TITLE
Unbreak loading translations

### PR DESCRIPTION
**Pull request by antonio-rojas**
Commit 18ddb9df4a1af290805835d2376b80b984d61766 changed SHAREDIR to point to CMAKE_INSTALL_DATADIR, which is a relative path by default. This prevents the C++ code from finding the translations at runtime.

### CODE REVIEW

**Comment by mgallien** [comment]
@antonio-rojas sorry for the delayed review due to the team being busy
coudl you have a look at the failed DCO check ?

**Review by mgallien — APPROVED** [review]

**Review by claucambra — APPROVED** [review]

**Pull request merged**
