### PR TITLE
Use full-bleed Start Tile

### LINKED ISSUE #2954: Start Menu Tile Enhancements?
Note: this is kind of an extension of Issue https://github.com/nextcloud/desktop/issues/22.

### Expected behaviour
When pinned to the main screen of the Start Menu, Nextcloud should show a full-bleed tile rather than an icon in front of a backdrop, at least when this is requested by Windows. (Microsoft has been redesigning the Start Menu, so the precise norms seem to be somewhat in flux.)

### Actual behaviour
When pinned to the main screen of the Start Menu, Nextcloud shows an icon in front of a backdrop.

### Steps to reproduce
1. Pin Nextcloud to the main screen of the Start Menu

### Client configuration
Operating system: Windows 10 (probably also applicable on Windows 8 and 8.1 for the Luddites)

I'm actually basing this on other people's screenshots, specifically @pkrolkgp's on Issue https://github.com/nextcloud/desktop/issues/2903:

106887169-11f8e400-66e5-11eb-835f-44e18c5c6855

Notice how both the Nextcloud application and Nextcloud folder icons are circles floating in the middle of their respective tiles (and it's not clear which is which). The more "native" behavior is reflected in this screenshot by Logitech Options and one of the icons in the HP icon stack.

In order to implement the full-bleed icons, I'm pretty sure all that's necessary would be replacing the following with full-bleed images (i.e. forgoing the circular mask):
* [150-Nextcloud-w10startmenu.png](https://github.com/nextcloud/desktop/blob/4cd77d96aef514df31773d5caf27c336f8afde59/theme/colored/150-Nextcloud-w10startmenu.png)
* [70-Nextcloud-w10startmenu.png](https://github.com/nextcloud/desktop/blob/4cd77d96aef514df31773d5caf27c336f8afde59/theme/colored/70-Nextcloud-w10startmenu.png)

I should clarify that this is somewhat a question of taste, having the full-bleed icons rather than the circular ones, but it would also have the added benefit of cleanly distinguishing the application from the folder, which was the issue presented in https://github.com/nextcloud/desktop/issues/2903. In other words, the application would be full-bleed, while the folder would use a derivative of the Windows folder icon.

### PR DESCRIPTION
**Pull request by elsiehupp**
Closes #2954; see also #22 and #2903.

I have not actually tested this to see if it works, because I don't currently have a Windows setup, so could someone else build these changes and see if they at least have their intended effect? I'm working from [this guide](https://www.askvg.com/tip-customize-start-screen-tiles-background-color-text-color-and-logo-in-windows-8-1/). I'm not sure if removing the explicit background color is a breaking change, but it seemed extraneous with a full-bleed icon.

As for the stylistic merits of using a full-bleed tile versus a masked icon, I'm not a Windows user, and I don't have the strongest opinions, but at the very least this change makes a pinned shortcut to the Nextcloud application visually distinct from a pinned shortcut to the Nextcloud folder. I'll do some digging to see how (or if) the Nextcloud folder icon is assigned, as described in #2903.

### CODE REVIEW

**Comment by elsiehupp** [comment]
I just realized this might create problems depending on how the manifest is created for OEMs, but it doesn't appear to be a template file.

**Review by jancborchardt — APPROVED** [review]
Looks good! :) Just to be sure, this uses the file from https://github.com/nextcloud/promo/blob/master/nextcloud-icon.svg, right?

I don’t have Windows to test, so @FlexW @allexzander need to check :)

**Comment by elsiehupp** [comment]
Hi Jan—what’s the current status of this? Should it be merged, or not? (I’m just checking in because I don’t have any obvious next steps here myself.)

**Comment by jancborchardt** [comment]
> Hi Jan—what’s the current status of this? Should it be merged, or not? (I’m just checking in because I don’t have any obvious next steps here myself.)

Design-wise this looks good, just the code and actual working on Windows has to be checked. :) cc @mgallien @FlexW @camilasan @allexzander

**Comment by jancborchardt** [comment]
@tobiasKaminsky @mgallien @camilasan @allexzander could you check this out?

@elsiehupp I assume this is still current and you only closed it because of lacking activity? Sorry!

**Comment by mgallien** [comment]
I am going to have a look quickly

**Review by mgallien — APPROVED** [review]
works great
thanks

**Comment by mgallien** [comment]
@elsiehupp can you rebase and then we merge it

**Pull request merged**
