### PR TITLE
Port from context properties to singletons

### PR DESCRIPTION
**Pull request by nicolasfella**
Context properties are deprecated and will be removed in Qt 6. QML singletons are the better option here, especially given that the types already are singletons.

Signed-off-by: Nicolas Fella <nicolas.fella@gmx.de>

### CODE REVIEW

**Comment by DominiqueFuchs** [comment]
See https://github.com/nextcloud/desktop/pull/1890#issuecomment-619355453 , I'll come back to this very shortly. Looks great, thanks!

**Comment by misch7** [comment]
Just a side note: I locally merged this PR with #1939 while debugging a crash in the other PR and noticed a new reproducible crash every time I quit the application.

Might be obsolete due to updating this branch / temporary local merge issues.

**Pull request merged**
