### PR TITLE
Use QML 5.12 everywhere.

### LINKED ISSUE #4069: Main dialog window does not open - Ubuntu
### Expected behaviour
Main dialog window should open when clicking either on:
- Open main dialog or
- See conflicts in setting window

### Actual behaviour
Main dialog does not open.

### Steps to reproduce
1.a Click in Next cloud logo  > Open main dialog
1.b (from settings window) Click on see conflicts.

### Client configuration
Client version: Desktop 3.4.0 (Ubuntu)

Operating system: Ubuntu 20.04

OS language: English

### PR DESCRIPTION
**Pull request by allexzander**
Signed-off-by: alex-z <blackslayer4@gmail.com>

This will fix #4069 and #4017

### CODE REVIEW

**Review by claucambra — APPROVED** [review]

**Review by mgallien — CHANGES_REQUESTED** [review]
let's not merge it as we require Qt 5.15 in our CMakeLists.txt files
thanks for the work, I am going to suggest packagers to use it

**Comment by mgallien** [comment]
@ivaradi Feel free to apply this PR to your Focal packaging branch
that should solve the issues with the main dialog not showing up

**Comment by allexzander** [comment]
@mgallien Seems to have worked (see last commit)

**Review by mgallien — CHANGES_REQUESTED** [review]
build is broken on Qt 5.12.10

**Pull request closed without merging**
