### PR TITLE
No need to translate ellipsis

### PR DESCRIPTION
**Pull request by rakekniven**
Here another PR for the same code line as #3238 

Signed-off-by: rakekniven <2069590+rakekniven@users.noreply.github.com>

### CODE REVIEW

**Review by Valdnet — APPROVED** [review]

**Comment by rakekniven** [comment]
> ClientSideEncryptionTest (Failed)

Do not know how to fix it. Is this related to my commit?

**Comment by FlexW** [comment]
@rakekniven I was too slow, but there are a few other occurrences of ellipses that do not need to be translated at:
src/gui/shareuserline.ui:148 and src/gui/shareuserline.ui:192.

**Comment by rakekniven** [comment]
> @rakekniven I was too slow, but there are a few other occurrences of ellipses that do not need to be translated at:
> src/gui/shareuserline.ui:148 and src/gui/shareuserline.ui:192.

Are you sure? There has been another commit in between by Valdnet.

**Comment by FlexW** [comment]
@rakekniven I checked it again and you are right. Everything is resolved now. Sorry.

**Pull request merged**
