### PR TITLE
When resynchronizing files, avoid truncating timestamp.

### PR DESCRIPTION
**Pull request by donaldsycamore**
#4139, #3456

Signed-off-by: Donald Gordon <donald@gordon.nz>

### CODE REVIEW

**Comment by donaldsycamore** [comment]
Failed test:

```
FAIL!  : TestSyncEngine::testDirectoryInitialMtime() Compared values are not the same
--
   Actual   (QFileInfo(fakeFolder.localPath() + "foo").lastModified()): 2022/01/31 22:57:24.831[UTC]
   Expected (datetime)                                                : 2022/01/31 22:57:24.000[UTC]
```

**Comment by donaldsycamore** [comment]
Making this only apply to files now, as a test failed due to it applying to directories

**Comment by donaldsycamore** [comment]
Pushing again, managed to push code with no changes!

**Comment by donaldsycamore** [comment]
@matthieugallien @allexzander I see you two are the major committers on cfapi, would either of you be able to build with this patch on Windows for me?

**Comment by allexzander** [comment]
> Failed test:
> 
> ```
> FAIL!  : TestSyncEngine::testDirectoryInitialMtime() Compared values are not the same
> --
>    Actual   (QFileInfo(fakeFolder.localPath() + "foo").lastModified()): 2022/01/31 22:57:24.831[UTC]
>    Expected (datetime)                                                : 2022/01/31 22:57:24.000[UTC]
> ```

@donaldsycamore 

Doesn't fail when I run it locally, but, it seems to be random? Can you add `datetime.addSecs(1);` after `datetime.setSecsSinceEpoch(datetime.toSecsSinceEpoch()); // wipe ms` and see if the failure is fixed for you?

**Review by allexzander — APPROVED** [review]
Seems legit

**Comment by allexzander** [comment]
> @matthieugallien @allexzander I see you two are the major committers on cfapi, would either of you be able to build with this patch on Windows for me?

@donaldsycamore I've made a build using your changes + adding that 1 second to the date in tests https://cloud.nextcloud.com/s/TApSWZfFfq5t6mq Seems to be working file/syncing back and forth, but, I couldn't test if it is fixing the mentioned issues as I couldn't reproduce them.

**Comment by donaldsycamore** [comment]
Thanks.  The test failed with my [initial patch](https://github.com/donaldsycamore/desktop/commit/a295b0c239c7f2627edc4d81647b2774fc62aedb), which didn't check if the item was a file.  The [current patch](https://github.com/nextcloud/desktop/pull/4236/commits/ba8ade3838c22d186cdab12ffff7195ee54f42d8) checks the file type, and still truncates directory timestamps.  That doesn't fail the test.  The timestamp truncation behaviour, for directories, is required to pass that test.

I'll test @allexzander's build locally with the shell snippet https://github.com/nextcloud/desktop/issues/4139#issuecomment-1022033564 to see if the problem is still there.

**Comment by donaldsycamore** [comment]
I've installed @allexzander's build ... and still the timestamps are truncated.

```
$ while [ 1 ] ; do echo "touch `date`" ; touch testfile2; for i in `seq 1 10` ; do ls -l --time-style=full-iso testfile2;sleep 1;done; done
touch Wed Feb  9 11:50:10 NZDT 2022
-rw-r--r-- 1 donald donald 0 2022-02-09 11:50:10.748874100 +1300 testfile2
-rw-r--r-- 1 donald donald 0 2022-02-09 11:50:10.748874100 +1300 testfile2
-rw-r--r-- 1 donald donald 0 2022-02-09 11:50:10.748874100 +1300 testfile2
-rw-r--r-- 1 donald donald 0 2022-02-09 11:50:10.748874100 +1300 testfile2
-rw-r--r-- 1 donald donald 0 2022-02-09 11:50:10.000000000 +1300 testfile2
-rw-r--r-- 1 donald donald 0 2022-02-09 11:50:10.000000000 +1300 testfile2
-rw-r--r-- 1 donald donald 0 2022-02-09 11:50:10.000000000 +1300 testfile2
-rw-r--r-- 1 donald donald 0 2022-02-09 11:50:10.000000000 +1300 testfile2
```

Next step is probably to find myself a Linux desktop to build and run this on to see if I can reproduce it in a more cogenial development environment.

**Comment by mgallien** [comment]
> I've installed @allexzander's build ... and still the timestamps are truncated.
> 
> ```
> $ while [ 1 ] ; do echo "touch `date`" ; touch testfile2; for i in `seq 1 10` ; do ls -l --time-style=full-iso testfile2;sleep 1;done; done
> touch Wed Feb  9 11:50:10 NZDT 2022
> -rw-r--r-- 1 donald donald 0 2022-02-09 11:50:10.748874100 +1300 testfile2
> -rw-r--r-- 1 donald donald 0 2022-02-09 11:50:10.748874100 +1300 testfile2
> -rw-r--r-- 1 donald donald 0 2022-02-09 11:50:10.748874100 +1300 testfile2
> -rw-r--r-- 1 donald donald 0 2022-02-09 11:50:10.748874100 +1300 testfile2
> -rw-r--r-- 1 donald donald 0 2022-02-09 11:50:10.000000000 +1300 testfile2
> -rw-r--r-- 1 donald donald 0 2022-02-09 11:50:10.000000000 +1300 testfile2
> -rw-r--r-- 1 donald donald 0 2022-02-09 11:50:10.000000000 +1300 testfile2
> -rw-r--r-- 1 donald donald 0 2022-02-09 11:50:10.000000000 +1300 testfile2
> ```
> 
> Next step is probably to find myself a Linux desktop to build and run this on to see if I can reproduce it in a more cogenial development environment.

not sure why you mention Linux but we automatically build an AppImage of your PR such that test is easy (see the comment with the link to download it)
I thought the problem was only triggered by using virtual files on Windows

**Comment by dsahlberg-apache-org** [comment]
Is there anything I can do to help push this forward?

**Comment by mgallien** [comment]
I am closing since the original bug has been fixed by a different approach

**Pull request closed without merging**
