### PR TITLE
ensure we do not modify a file that has been just uploaded

### PR DESCRIPTION
**Pull request by mgallien**

### CODE REVIEW

**Review by allexzander — CHANGES_REQUESTED** [review]
@mgallien The PR title mentions a file that has been uploaded, but in your code the changes are within `if (item->_direction == SyncFileItem::Down)` downloaded file, is this correct?

**Comment by mgallien** [comment]
> @mgallien The PR title mentions a file that has been uploaded, but in your code the changes are within `if (item->_direction == SyncFileItem::Down)` downloaded file, is this correct?
> 
> UPDATE: Also, `SyncEngineTest` has failed

basically the issue is that with group folders, when you upload a file, on the next sync, there will be an update metadata sync step from the server
on this down sync of metadata, we also update the mod time even if it is equal to the one from server
the result on windows is that you will truncate milliseconds from the modtime and will result in software thinking the file was modified

**Review by allexzander — APPROVED** [review]

**Pull request merged**
