### PR TITLE
Removed server versions as they are mostly outdated.

### PR DESCRIPTION
**Pull request by rakekniven**
Addionally added link to server wiki page.

Signed-off-by: rakekniven <2069590+rakekniven@users.noreply.github.com>

### CODE REVIEW

**Comment by mgallien** [comment]
thanks for the help but in fact the current state of which server versions are supported is more complex than what is in the doc
we indeed support server version 16 as the real minimum one
so the whole paragraph is invalid
not sure how I would fix it

**Comment by rakekniven** [comment]
From my point of view the docs are describing the community version. AFAIK you have support docs behind a customer login.
The community version of the server is supporting three major versions. Therefore the change is an improvement to the current listing, or?

**Comment by tobiasKaminsky** [comment]
For community it is correct and this is what we should communicate.
For customers it might be different, but this is then an individual contract.

**Review by tobiasKaminsky — APPROVED** [review]

**Comment by rakekniven** [comment]
I cannot fix SonarCloud test. No rights to do something.

**Comment by mgallien** [comment]
> I cannot fix SonarCloud test. No rights to do something.

this check is not needed anyway for a documentation PR

**Review by mgallien — APPROVED** [review]

**Comment by mgallien** [comment]
@rakekniven will merge it myself as I want to have your commits be squashed and cannot write to your clone to do it

**Comment by mgallien** [comment]
merged by https://github.com/nextcloud/desktop/commit/66ba89a37df506bf3f76b83db222668e3636bf7b

**Pull request closed without merging**
