### PR TITLE
put VFS plugins into the correct path

### PR DESCRIPTION
**Pull request by mgallien**
Signed-off-by: Matthieu Gallien <matthieu.gallien@nextcloud.com>

### CODE REVIEW

**Comment by FlexW** [comment]
That will still leave make install broken.

**Review by FlexW — APPROVED** [review]

**Comment by FlexW** [comment]
Also, we need to make the change in brander. Otherwise, it will have no effect.

**Review by allexzander — APPROVED** [review]

**Comment by mgallien** [comment]
> That will still leave make install broken.

I agree but fixing that looked like another task (and I am not sure this used to work before VFS plugins)

**Comment by FlexW** [comment]
> > That will still leave make install broken.
> 
> I agree but fixing that looked like another task (and I am not sure this used to work before VFS plugins)

It worked. That's how all the Linux distros build the package :)

**Comment by mgallien** [comment]
> > > That will still leave make install broken.
> > 
> > 
> > I agree but fixing that looked like another task (and I am not sure this used to work before VFS plugins)
> 
> It worked. That's how all the Linux distros build the package :)

I guess Debian at least carry quite some patches https://salsa.debian.org/owncloud-team/nextcloud-desktop/-/tree/master/debian/patches

**Comment by FlexW** [comment]
> > > > That will still leave make install broken.
> > > 
> > > 
> > > I agree but fixing that looked like another task (and I am not sure this used to work before VFS plugins)
> > 
> > 
> > It worked. That's how all the Linux distros build the package :)
> 
> I guess Debian at least carry quite some patches https://salsa.debian.org/owncloud-team/nextcloud-desktop/-/tree/master/debian/patches

But that's debian ;) Arch Linux for example nearly does a cmake make make install
https://github.com/archlinux/svntogit-community/blob/packages/nextcloud-client/trunk/PKGBUILD
We even rely in our own build-app-image script on make install that it puts libs and executables in the correct directories.

**Pull request merged**
