### PR TITLE
🎨 Update icons to latest Hub 9 style

### LINKED ISSUE #7039: [Style] Update icons on sharing view
### How to use GitHub

|Desktop|Web v30|
|---|---|
|2024-08-27 17_17_33-NVIDIA GeForce Overlay|2024-08-27 17_31_50-NVIDIA GeForce Overlay|

updated icons for:
* [link share](https://fonts.google.com/icons?icon.query=link&selected=Material+Symbols+Outlined:link:FILL@0;wght@400;GRAD@0;opsz@24&icon.size=24&icon.color=%23e8eaed)
* [external link](https://fonts.google.com/icons?icon.query=link&selected=Material+Symbols+Outlined:link:FILL@0;wght@400;GRAD@0;opsz@24&icon.size=24&icon.color=%23e8eaed)
* [copy icon](https://fonts.google.com/icons?icon.query=copy&selected=Material+Icons+Outlined:content_copy:&icon.size=24&icon.color=%23e8eaed&icon.set=Material+Icons)

### PR DESCRIPTION
**Pull request by AndyScherzinger**
... Material Symbols

Resolves #7039

### CODE REVIEW

**Review by jancborchardt — APPROVED** [review]
Looks good!

**Review by claucambra — APPROVED** [review]
awesome :)

**Comment by AndyScherzinger** [comment]
@mgallien done... all icons should now be up-to-date with the server's icons shipping with Hub 9 🎉

**Pull request merged**
