### PR TITLE
Show a broken lock icon for unencrypted subdirectory

### PR DESCRIPTION
**Pull request by ivan-cukic**
The E2E application allows creating unencrypted subdirectories
in an encrypted parent. This is a big privacy problem.

This patch shows a red broken lock icon for these subdirectories
in the NC client UI.

Screenshot_20190514_214818

### CODE REVIEW

**Comment by ivan-cukic** [comment]
P.S. This will be important even when #774 gets fixed for as long as the E2E application allows unencripted subdirectories.

**Comment by jancborchardt** [comment]
> The E2E application allows creating unencrypted subdirectories
in an encrypted parent. This is a big privacy problem.

Rather than putting an indicator there which might never be found, shouldn’t this be prevented in the first place? cc @rullzer @tobiasKaminsky

**Comment by ivan-cukic** [comment]
I agree this situation should be prevented on the server side. Until it is, this is a privacy problem.

Another place where this can be exposed is the notification area - the e2e server module can show a warning notification about this. Then, the user will be able to open the NC client and see which directories are problematic.

**Comment by tobiasKaminsky** [comment]
This is a bug and I hope it is only a small patch to solve it.
On android when creating a file, I check if the current or any parent folder (up to root) is encrypted. If so, I treat the current directory also as encrypted.
Same needs to be done on desktop.
We stated in RFC that all subfolders are automatically encrypted.



> I agree this situation should be prevented on the server side.

This cannot be solved on server side, as the most security impact we assume is that an admin modified the e2e server app, so we cannot trust them ever. 
Thus for checking for encryption state we need to do this locally (as explained above).

**Comment by tobiasKaminsky** [comment]
@camilasan can you have a look into this and fix the problem with unencrypted e2e folders?
@jancborchardt Roeland is (more or less) not doing desktop, so if you have any desktop related stuff please ping Camila.

**Comment by ivan-cukic** [comment]
I was planning to do that next. No need to bother @camilasan 

Even if all clients start behaving correctly - automatically encrypt subfolders, it is still a security issue.

E2E allows users to feel safe even when they have a malicious admin. The admin can create an unencrypted directory in a user's encrypted one. If the clients do not expose this information somehow, the user will eventually store sensitive data in that directory. The android client even marks the subdirectory with a 'lock' icon even if it is not encrypted.

Next, even if all clients under github.com/nextcloud start automatically encrypting subdirectories, someone could create an unofficial client (for Sailfish OS, for example) and that (by error) does not do so. Which would lead to the same problem as above.

Maybe this can be moved to a private security-issue-related list - there are a few more problems with the current RFC.

**Comment by tobiasKaminsky** [comment]
> The admin can create an unencrypted directory in a user's encrypted one.

This is true, but as the client has the information that the parent folder is encrypted it must encrypt also the subfolder.
As said, we cannot trust the admin/server at all in a E2E scenario.



> Maybe this can be moved to a private security-issue-related list - there are a few more problems with the current RFC.

Just shoot me an email to tobias at nextcloud dot com and we can discuss this.

**Comment by camilasan** [comment]
I think this is a nice improvement. Did you @tobiasKaminsky discuss with @ivan-cukic anything else via email? May I merge this?

**Comment by tobiasKaminsky** [comment]
Can you test this
- create a folder e2e
- set it up
- create a new subfolder in "e2e"
- see if this is recognized as encrypted even if no file is in it

**Comment by camilasan** [comment]
Ok @tobiasKaminsky I can. If it works, anything against it?

**Comment by camilasan** [comment]
@tobiasKaminsky 

notencrypted

**Comment by tobiasKaminsky** [comment]
Well…this now is misleading and might scare people.
In this scenario "rock" will get encrypted once any client will upload a file.
And therefore it should be shown as encrypted, or?

Only IF (due to a bug or whatever) there are files in a subfolder AND it is really not encrypted it should show it to user as a warning.
(and yes, this could happen due to faulty 3rd party clients, hack of an admin, etc. and therefore it is good to have it)

**Comment by 1989gironimo** [comment]
Awesome, stalebot as a reminder! :)

**Comment by 1989gironimo** [comment]
Still pending!

**Pull request merged**
