### PR TITLE
nav pane usability

### PR DESCRIPTION
**Pull request by peacepenguin**
Changes the text shown in the Navigation pane when more than one account is configured. Uses an assembled name from human readable variables. This fixes an issue seen when using LDAP backend users, where the users GUID is shown instead of the normal username and url as is seen when not using LDAP backend users. Fixes issue: https://github.com/nextcloud/desktop/issues/3305

Signed-off-by: Ben <peacepenguin@users.noreply.github.com>

### CODE REVIEW

**Comment by mgallien** [comment]
@peacepenguin sorry for the big delay to review your contribution
I added our designers in the review
can you please share a screenshot before and after to show the difference for them such that they do need to build themselves ?

**Comment by peacepenguin** [comment]
I would love to take screenshots of these changes, but I can no longer build the client on windows. Attempting the cross compile steps on linux also fails, as the Docker image referenced in those instructions no longer exists on docker hub.

I would love to see the code and automation steps used that builds the Daily Windows MSI's availalbe for download. That system seems to work well and I'd like to build the way the Daily's are being built, but I can't find any reference to how that CI system is configured.

Previously the "client-building" steps worked for me, but those are now broken too. I'd prefer to build on linux like the "cross compile" instructions imply is possible, but those instructions reference a dead docker image for opensuse, so that can't be the right way either.


https://github.com/nextcloud/desktop/blob/master/doc/building.rst#windows-development-build
-- does not work, errors out with CMake was unable to find a build program corresponding to "MinGW Makefiles".

https://github.com/nextcloud/desktop/blob/master/doc/building.rst#windows-installer-ie-deployment-build-cross-compile
-- does not work, errors out on the docker build step, the docker file references a non-existent opensuse version 42 from docker hub.  These instructions appear VERY out of date, opensuse version 42 has been removed entirely from the docker repo that the Docker file references as the base.

https://github.com/nextcloud/client-building/blob/master/README.md
-- does not work, errors out with missing inkscape libraries (inkscape is not documented as a prereq anywhere, something isn't right)

**Comment by peacepenguin** [comment]
build in progress, screenshots will be added soon. 

I finally found the issue with inkscape being a new build requirement and where to reference it in the build when building on windows. Still curious how the linux-windows cross-compiling works, if it works at all anymore, can't get that method to work still due to undocumented changes to the opensuse docker images referenced in the docs.

**Comment by jancborchardt** [comment]
> build in progress, screenshots will be added soon.

Feel free to ping me when this is done, then I can do a design review :)

**Review by claucambra — COMMENTED** [review]
Code-wise this looks good @peacepenguin are you still interested in having this merged? :)

**Comment by peacepenguin** [comment]
I ran into an issue where the name and folder name showed completely blank in cases where nextcloud was using saml+ldap. So this probly should be closed and revisited later, as I never got to the bottom of that issue myself. It would be seen as a regression if merged as is for people using user_saml and ldap together.

**Comment by Rello** [comment]
Hello,

Thank you for your contribution to the Desktop Client with this pull request.
We are closing this request as it is outdated, no longer relevant (e.g., due to Qt 6), or does not align with the current roadmap.

We truly value your support and hope to see more contributions from you in the future!


Best regards,
Nextcloud Desktop Team

**Pull request closed without merging**
