### PR TITLE
l10n: Remove double space and sort sentence

### PR DESCRIPTION
**Pull request by Valdnet**
Signed-off-by: Valdnet <47037905+Valdnet@users.noreply.github.com>

### CODE REVIEW

**Review by rakekniven — APPROVED** [review]

**Review by FlexW — APPROVED** [review]
Thanks :)

**Comment by mgallien** [comment]
@Valdnet please fix the missing DCO. I cannot merge your work without it

**Comment by Valdnet** [comment]
@mgallien Fixed DCO 😉.

**Review by mgallien — CHANGES_REQUESTED** [review]
Please use your own email instead of masquerading as Felix

**Comment by Valdnet** [comment]
@mgallien Is my email address visible now?

**Comment by Valdnet** [comment]
@allexzander I cannot merge. Does not end the fixupbot task.

**Comment by Valdnet** [comment]
Closed due to new PR #3620.

**Pull request closed without merging**
