### PR TITLE
Simplify cmake command to make copy-pastable

### PR DESCRIPTION
**Pull request by jancborchardt**
@camilasan this is what I used some time ago for setting up. For me it worked and made the dev setup process much much simpler. (I think we talked about it some months ago, found I didn’t open a pull request for it back then.)

Please review @nextcloud/desktop

### CODE REVIEW

**Comment by camilasan** [comment]
Thanks @jancborchardt, could you rebase the PR?

**Comment by camilasan** [comment]
Inspiders by your PR I did change the instructions in the wiki:
https://github.com/nextcloud/desktop/wiki/How-to-compile-the-desktop-client

What do you think @jancborchardt?

**Comment by jancborchardt** [comment]
@camilasan looks good, but now the command is not copypastable anymore? As `$PATH` does not refer to the environment variable but instead the text you wrote above? I would really go for dead-simple setup, that’s why I just went with `~/desktop-install/` as default path. For people who know how to do it they can still easily change it, for people who just want to build it it will just work. :)

**Comment by camilasan** [comment]
> @camilasan looks good, but now the command is not copypastable anymore? 

I will fix it.

> As `$PATH` does not refer to the environment variable but instead the text you wrote above? 

ok, PATH was a bad idea.

> I would really go for dead-simple setup, that’s why I just went with `~/desktop-install/` as default path. For people who know how to do it they can still easily change it, for people who just want to build it it will just work. :)

My goal was to make it generic.

**Pull request merged**
