### PR TITLE
Feature/add edit button

### PR DESCRIPTION
**Pull request by marimeireles**
WIP: #1524 

So @camilasan can check my progress :)

### CODE REVIEW

**Comment by jancborchardt** [comment]
@marimeireles is this based on what @camilasan did at https://github.com/nextcloud/desktop/pull/1442 or does it replace it? Or is both needed? :)

**Comment by marimeireles** [comment]
As far as I'm concerned this is a different thing. Gonna try to work on this now, sorry, I was on vacation and lost track of things.

**Comment by marimeireles** [comment]
But wait a second.. @camilasan is this still relevant for the new NextCloud desktop version?

**Comment by jancborchardt** [comment]
@marimeireles yeah it should be, or why not? :) Are you referring to Virtual drive, or the new tray menu? Neither of those make a right-click → Edit functionality obsolete, as far as I can see. :)

**Comment by er-vin** [comment]
Doesn't apply anymore on master, a new approach would need to be taken. Please feel free to open a new PR related to that and sorry for that lost effort...

**Pull request closed without merging**
