### PR TITLE
 Add Upload & download speed rate on nextcloud window after estimated time #4388

### PR DESCRIPTION
**Pull request by tokun-mobica**
PR related to request [Add Upload & download speed rate on nextcloud window after estimated time #4388 ](https://github.com/nextcloud/desktop/issues/4388)

### CODE REVIEW

**Comment by mgallien** [comment]
@tokun-mobica will try to review it tomorrow
thanks for the contribution !

**Comment by nimishavijay** [comment]
Super nice work @tokun-mobica ! Thank you for contributing :)
I would say that showing all the sync information in the main dialogue is a lot of info, especially since much of that is shown in the settings dialogue anyway. We could use a tooltip in the main dialogue though :) 

I suggest we show the info in the tray menu with the middle dot separator (this character · )

`209 MB of 529 MB (2.4MB/s) · 59 seconds left`

and in the tray menu tooltip we could show the upload and download speed, maybe in a clearer way:

```
Syncing "nc_file_test.zip", "nc_test1.zip"
Upload 2 MB/s
Download 4 MB/s
```
The same tooltip could be used in the settings dialogue as well :)

**Comment by AndyXheli** [comment]
Hi all, I just wanted to see if we have an update on this project?

**Comment by AndyXheli** [comment]
Hi all just wanted to see if there's any progress on this?

**Comment by AndyXheli** [comment]
Hi all just wanted to see if there's any progress on this?

**Comment by Rello** [comment]
Hello,

Thank you for your contribution to the Desktop Client with this pull request.
We are closing this request as it is outdated, no longer relevant (e.g., due to Qt 6), or does not align with the current roadmap.

We truly value your support and hope to see more contributions from you in the future!


Best regards,
Nextcloud Desktop Team

**Pull request closed without merging**
