### PR TITLE
l10n: Replace apostrophe with double quotation

### PR DESCRIPTION
**Pull request by Valdnet**

### CODE REVIEW

**Review by rakekniven — APPROVED** [review]

**Comment by rakekniven** [comment]
Wäre es möglich solche commits in einem branch zu sammeln und nicht jeden commit einzeln als PR zu behandeln?

Das würde Arbeit und E-Mails sparen.

Was denkst Du darüber?

**Comment by Valdnet** [comment]
@rakekniven This commit is a sequel to PR #3350 as there was a conflict. I decided to add this change in a separate commit.

**Comment by FlexW** [comment]
This one brokes the tests too :( needs some manual work

**Comment by Valdnet** [comment]
@FlexW Hmmm… I don't know what to do next.

**Comment by Valdnet** [comment]
@allexzander I cannot merge. Does not end the fixupbot task.

**Comment by allexzander** [comment]
@Valdnet I am going to have to ask you to close this PR and open a new one again. As I've already mentioned, we do not allow Merging master into another branch. You must always use `rebase` against master in this repo.

**Review by allexzander — CHANGES_REQUESTED** [review]
Merge is not allowed. Please, use rebase instead. https://www.atlassian.com/git/tutorials/merging-vs-rebasing

**Comment by Valdnet** [comment]
Closed due to new PR #3620.

**Pull request closed without merging**
