### PR TITLE
we run on Windows 8.1+

### PR DESCRIPTION
**Pull request by mgallien**
Signed-off-by: Matthieu Gallien <matthieu.gallien@nextcloud.com>

### CODE REVIEW

**Comment by mgallien** [comment]
as a reference https://github.com/nextcloud/nextcloud.com/pull/1565#issuecomment-966929183

**Comment by mgallien** [comment]
@jospoortvliet going to push this after you merged the same change on website

**Review by FlexW — APPROVED** [review]

**Review by tflidd — APPROVED** [review]

**Pull request merged**
