### PR TITLE
[Locales] Fix gh workflow

### PR DESCRIPTION
**Pull request by pierreozoux**
Fixes https://github.com/nextcloud/desktop/pull/4252 sorry :/

### CODE REVIEW

**Review by mgallien — APPROVED** [review]

**Review by allexzander — APPROVED** [review]

**Comment by pierreozoux** [comment]
Hey @mgallien!

I found a way to test my gh action, and I managed to make it work.

But now, I have a dilemma.

I think the cleanest would be to allow the gh action to push the result of `cd doc && make gettext` directly to the master branch.
But this would need 2 things:
 - admin are allowed to push directly to master
 - and we put an admin token as a secret for the gh action to use to push to master
(This is described [here](https://github.com/actions/checkout/issues/344#issuecomment-801724874)

I find it the cleanest, but I understand that it has security implication.

The second option is to use a PR and auto approve it, it is what we have in the documentation folder:
 - [PR part](https://github.com/nextcloud/documentation/blob/master/.github/workflows/generate_catalog_templates.yml#L20-L24)
 - but I just realized, the auto approve is currently broken :/

What is your opinion?

**Comment by mgallien** [comment]
> Hey @mgallien!
> 
> I found a way to test my gh action, and I managed to make it work.
> 
> But now, I have a dilemma.
> 
> I think the cleanest would be to allow the gh action to push the result of `cd doc && make gettext` directly to the master branch. But this would need 2 things:
> 
>     * admin are allowed to push directly to master
> 
>     * and we put an admin token as a secret for the gh action to use to push to master
>       (This is described [here](https://github.com/actions/checkout/issues/344#issuecomment-801724874)
> 
> 
> I find it the cleanest, but I understand that it has security implication.
> 
> The second option is to use a PR and auto approve it, it is what we have in the documentation folder:
> 
>     * [PR part](https://github.com/nextcloud/documentation/blob/master/.github/workflows/generate_catalog_templates.yml#L20-L24)
> 
>     * but I just realized, the auto approve is currently broken :/
> 
> 
> What is your opinion?

I am sorry to ask you more work but I guess I would prefer the auto approved PR as this is what we are supposed to have in the server (if I understand correctly)
this is also probably safer in case of troubles

**Comment by mgallien** [comment]
@pierreozoux nice ping
if I understand correctly more work is needed here
I think your contribution would be highly appreciated

**Comment by p-bo** [comment]
@pierreozoux
> * but I just realized, the auto approve is currently broken :/
Only to be sure that understood correctly - broken is GitHub component/addon itself (is it this? https://github.com/hmarr/auto-approve-action/issues ) or way how it is used in Nextcloud development workflow please?

@mgallien is implementation of merging of server docs and UI strings translations (which are already functional) also under such strict policy as demanded here for this attempt for adding of client docs translation please? It would be unfortunate to block newly added areas to translate only due different demands then and now, probably.

**Comment by pierreozoux** [comment]
Ok, I found some time to rework on this piece.

I'm trying to fix user documentation [here](https://github.com/nextcloud/documentation/pull/8316).

Once it is done, I'll replicate here.

I'll close this PR in the mean time.

**Comment by pierreozoux** [comment]
@mgallien can you approve the other PR?
https://github.com/nextcloud/documentation/pull/8316 ?

Thanks :)

**Comment by p-bo** [comment]
@mgallien
> if I miss the ping, please ping me again smile

As you suggested, pinging you again regarding https://github.com/nextcloud/documentation/pull/8316 due this message on Transifex:

> Scheduled maintenance on Sunday, 22nd of May from 06:00 (UTC) until 12:00 (UTC). During this time Transifex application will be offline.

To ideally start sync with Transifex before this outage and thus be able to start translating on this weekend already.

Thanks :-)

**Comment by p-bo** [comment]
> Ok, I found some time to rework on this piece.
> 
> I'm trying to fix user documentation [here](https://github.com/nextcloud/documentation/pull/8316).
> 
> Once it is done, I'll replicate here.
> 
> I'll close this PR in the mean time.

@pierreozoux 
Hi, it seems, that in documentation repo is automatic approving working great now after all your work - https://github.com/nextcloud/documentation/pulls?q=is%3Apr+is%3Aclosed - good work!

So would it be possible to replicate in this repository to be able to advance on https://github.com/nextcloud/desktop/issues/3234 please?

Many thanks and sorry for I'm unable to help more than tracking all of this and translating then into my native language :-)

**Pull request closed without merging**
