### PR TITLE
Schedule feature

### PR DESCRIPTION
**Pull request by esguti**
See issue #198

### CODE REVIEW

**Comment by camilasan** [comment]
hey @esguti, why did you close the PR? :)

**Comment by esguti** [comment]
> hey @esguti, why did you close the PR? :)

Yes, it was not well merged. I will make another merge this night. Should I include Spanish translation?

**Comment by camilasan** [comment]
> > hey @esguti, why did you close the PR? :)
> 
> Yes, it was not well merged. I will make another merge this night. Should I include Spanish translation?

Ok, good :) The translations are handled via Transifex. Just make sure to call tr() for the strings. thanks!

**Comment by esguti** [comment]
OK, thanks @camilasan

**Pull request closed without merging**
