### PR TITLE
Revert DEFAULT_REMOTE_POLL_INTERVAL back from 5 seconds to 30 seconds

### PR DESCRIPTION
**Pull request by andwun**
I noticed the following issue:

* In #1115 it was asked to remove the minimum limit for the remote poll interval
* In #1234 the default remote poll interval (`DEFAULT_REMOTE_POLL_INTERVAL`) has been lowered from 30 seconds to 5 seconds while referring to #1115 
* The docs at [1] still state that 30 seconds is the default for the config option remotePollInterval

Polling every 5 seconds for changes by default is a waste of resources.
Therefore with this PR, I would argue it would be best to revert the default back to 30 seconds.

[1] https://docs.nextcloud.com/desktop/2.5/advancedusage.html

### CODE REVIEW

**Comment by andwun** [comment]
@misch7 

> I don't know the specific reason for reducing it to 5 seconds. My first guest would be user's impatience for syncs? ^^

I think the user that implemented #1234 simply misunderstood what was requested in #1115:

It was never requested to lower the default for the remote poll interval to 5 seconds.
Instead #1115 asks to remove the limit that enforces a 5 second minimum for the remote poll interval, when the client is configured to update more often than that, say every 2 seconds.

**Comment by misch7** [comment]
@andwun Thanks for pointing this out.

So I'll merge this here - let's see when users complain about their 30 sec. wait period 😅😇

But heck, we're doing it for the servers 😼

**Comment by misch7** [comment]
🍒 Cherry-picked to stable-2.6

**Comment by DasSkelett** [comment]
I guess this closes https://github.com/nextcloud/desktop/issues/1567 too?

**Pull request merged**
