### PR TITLE
Bring back .lnk files on Windows and always treat them as non-virtual files.

### LINKED ISSUE #3244: [3.2.1 regression] Shortcut .lnk files cannot be synced anymore
I just installed 3.2.1 and I have the feeling that previously, .lnk files (shortcut in Windows) were synced (at least that I could remove these files from the **Ignored Files** list.

On 3.2.1, I can't force the sync anymore.

Am I wrong?

### PR DESCRIPTION
**Pull request by allexzander**
Fix #3244 

Signed-off-by: alex-z <blackslayer4@gmail.com>

### CODE REVIEW

**Comment by mgallien** [comment]
this solution looks interesting.
I am going to test it in the next days

**Comment by tobiasKaminsky** [comment]
Sounds promising!

**Comment by allexzander** [comment]
> this solution looks interesting. I am going to test it in the next days

I have tested it with different scenarios. Seems to be working.

**Review by claucambra — APPROVED** [review]

**Pull request merged**
