### PR TITLE
Feature/scheduler

### LINKED ISSUE #198: add sync schedule to run only during certain times
the cloud sync app from a synology NAS has this where you can drag the mouse over a 7 line grid to mark the hours when syncing is enabled. 

image

This is particularly useful for those in remote areas with satellite internet and contracts that give them unlimited data quota during certain hours of the night.

### PR DESCRIPTION
**Pull request by esguti**
Fix #198

### CODE REVIEW

**Comment by DominiqueFuchs** [comment]
Thanks a lot for contributing @esguti ! 
I do not have any strong opinions about this feature atm, but the maintainer surely will chime in, as they already noticed your issue. Few things that came to my mind though, if we're going to implement this:

- The settings file is very loaded with redundant entries with the current schedule format. Maybe it would be more usefull to implement a small regex or parser-helperfunction to store and load the schedule settings to reduce these lines to just one or two (simply sync times with range format, comma separated)
- The table view for the schedule GUI should auto expand vertically I think, right now it leaves some space of the UI widget below unused
- The cell heights/widths can be a little wider, as there are cutoffs of the numbers on my screens

I took a frew screens for the people who do not yet have time to build a test client with your branch yet, this is generally a good idea when implementing UI changes:
Scheduler1
Scheduler2
Scheduler3

**Comment by esguti** [comment]
Thanks Dominique for your comments!.

I will optimize the configuration as you suggested.

Regarding the auto-expand, I am not able to reproduce the behavior you are describing, in my case, I can not make the window so small that the crossbars appear, could it be the O.S. version? I am using Ubuntu 18.04.3 LTS

screencast_nextcloud_client

**Comment by jancborchardt** [comment]
UI-wise this should not be so present as a tab in the top bar, as the default is for sure just to sync everything all the time.

I see it more as a "Schedule syncing" button in `General → Advanced` next to the "Edit ignored files" button. Also opening a new window, with the content fo the scheduler.

There should never be either horizontal or vertical scrollbars, the content should fit the window. :)

**Comment by esguti** [comment]
> UI-wise this should not be so present as a tab in the top bar, as the default is for sure just to sync everything all the time.
> 
> I see it more as a "Schedule syncing" button in `General → Advanced` next to the "Edit ignored files" button. Also opening a new window, with the content fo the scheduler.
> 
> There should never be either horizontal or vertical scrollbars, the content should fit the window. :)

I can also add the option "Schedule syncing" in the contextual menu of the sync:

contextualmenu

I am busy with another project right now, but I will implement the changes and submit a new merge request  asap. You can close this merge request if you want, or I will when the new submission is ready.

**Comment by camilasan** [comment]
> You can close this merge request if you want, or I will when the new submission is ready.

I think you can continue working in the same PR @esguti :)
Thanks!

**Comment by esguti** [comment]
Almost done, just need to compile and test on MAC
nextcloud_desktop_screencast2

**Comment by jancborchardt** [comment]
Some design feedback:
- Let’s only have this globally for now, as per-account is too confusing (fun fact, until now I had no idea that there is a global ignore list and account-specific one …)
- The button should be called "Edit sync schedule", and the title "Sync schedule"
- In the dialog, the "Schedule Settings" container and heading is not needed.
- "Enable" can be called "Enable sync schedule"
- The "Suspend" and "Run" wording is a bit strange. Let’s use "Pause" and "Sync" instead, to use the language we use elsewhere
- Let’s move the "Pause" and "Sync" legend a bit to the left so it’s flush with the other things. Also best put "Sync" to the left so the "Pause" white box is not mistaken for a checkbox.
- Better label for the "OK" button is "Save sync settings"
- Default is all blue/sync, right?
- What’s the 2 different shades of blue?

Good stuff! What do you think @DominiqueFuchs @penCsharpener

**Comment by esguti** [comment]
> Some design feedback:
> 
>     * Let’s only have this globally for now, as per-account is too confusing (fun fact, until now I had no idea that there is a global ignore list and account-specific one …)
> 
>     * The button should be called "Edit sync schedule", and the title "Sync schedule"
> 
>     * In the dialog, the "Schedule Settings" container and heading is not needed.
> 
>     * "Enable" can be called "Enable sync schedule"
> 
>     * The "Suspend" and "Run" wording is a bit strange. Let’s use "Pause" and "Sync" instead, to use the language we use elsewhere
> 
>     * Let’s move the "Pause" and "Sync" legend a bit to the left so it’s flush with the other things. Also best put "Sync" to the left so the "Pause" white box is not mistaken for a checkbox.
> 
>     * Better label for the "OK" button is "Save sync settings"
> 
>     * Default is all blue/sync, right?
> 
>     * What’s the 2 different shades of blue?
> 
> 
> Good stuff! What do you think @DominiqueFuchs @penCsharpener

Thanks for the feedback, I have implemented all your points, except the label for the OK button. I changed it just for "Save" because "Save sync settings" in my opinion is long and redundant.

Regarding the 2 different shades of blue, one was for the default (previous) values, but I have removed it, it was confusing.

Check these screenshots and let me know your thoughts:

Screenshot from 2019-11-04 22-30-34
Screenshot from 2019-11-04 22-33-13

I hope to be able to test on macOS this week.

**Comment by jancborchardt** [comment]
Cool! Here’s some more feedback:
- The dialog title is better as "Sync schedule"
- This extra container in the dialog around everything (the border) can be removed, no?
- Instead of "Enable sync schedule", to be super clear, the checkbox could be labeled "Use schedule instead of always syncing"
- The "Restore defaults" button seems to be unnecessary. The default is to always sync, which is achieved by unchecking the "Use schedule …" checkbox.
- The look of the table is a bit boxy, especially the day/hour rows which even have a "button" style to it. The previous screenshot at https://github.com/nextcloud/desktop/pull/1453#issuecomment-535877287 looked a bit simpler and nicer?

What do you think? :)

**Comment by esguti** [comment]
> Cool! Here’s some more feedback:
> 
>     * The dialog title is better as "Sync schedule"
Done!
> 
>     * This extra container in the dialog around everything (the border) can be removed, no?
I managed to remove the border with a stylesheet.
> 
>     * Instead of "Enable sync schedule", to be super clear, the checkbox could be labeled "Use schedule instead of always syncing"
I see you like long labels :D ... I have copied the design of the  "Ignored Files Editor" dialog. This dialog has an explanation about the behaviour.
> 
>     * The "Restore defaults" button seems to be unnecessary. The default is to always sync, which is achieved by unchecking the "Use schedule …" checkbox.

Restore defaults, restores the previous configuration. The ButtonBox follows the same design that the ButtonBox in "Ignored Files Editor". I think it is useful, if not, you have to close the dialog and open it again to recover the configuration.
> 
>     * The look of the table is a bit boxy, especially the day/hour rows which even have a "button" style to it. The previous screenshot at [#1453 (comment)](https://github.com/nextcloud/desktop/pull/1453#issuecomment-535877287) looked a bit simpler and nicer?

I haven't change the look of the table, maybe it is the resolution of the screenshot that make it looks different. 
> 
> 
> What do you think? :)

Thanks again :+1: 

Screenshot from 2019-11-05 21-38-35
Screenshot from 2019-11-05 21-39-02
Screenshot from 2019-11-05 21-39-21

**Comment by jancborchardt** [comment]
The ignore list dialog is not a particularly good baseline cause we never really went over the design of hat. :) Please ignore it as a benchmark.

- Could you use the checkbox label that I mentioned? It’s clear and doesn’t need a subline
- The title is "Sync Schedule Editor", but should be "Sync schedule"
- As said the "Restore defaults" button is unneeded in this dialog
- The width of the content does not extend to the sides as far as the buttons do, is that possible to fix?
- Can the 3D-effect be removed from the heading row / column of the table?

Thanks a lot! :)

**Comment by esguti** [comment]
Done!

It has been difficult to have same color in header row and col, but finally I managed to do it using style sheets and an abstract button.

Screenshot from 2019-11-07 21-47-54

**Comment by esguti** [comment]
I hope to test it on macOS tomorrow

**Comment by esguti** [comment]
> Looks good to me design-wise now! +1

Thanks @jancborchardt for all your feedback

**Comment by esguti** [comment]
Tested on macOS ;)

**Comment by er-vin** [comment]
Sorry you didn't get any reply in a long time, we're still interested in this feature. Do you feel like rebasing this on current master and see how it goes?

**Comment by esguti** [comment]
Is it going to be approved by @camilasan and @misch7? I would not like to dedicate more time if it is not going to be included

**Comment by er-vin** [comment]
> Is it going to be approved by @camilasan and @misch7? I would not like to dedicate more time if it is not going to be included

This is understandable, and yes the goal is to get it in, that's why I asked you if you could revisit it. Clearly it needs a rebase.

**Comment by stratege1401** [comment]
any updated on this ??  also linked to #96

**Comment by mgallien** [comment]
@esguti   Do you still plan to work on this or should we just close it ?
As a first step, could you rebase on latest master ?
Our goal is still to get this in

**Comment by esguti** [comment]
Sorry, I don't have time right now to continue with this feature.

**Pull request closed without merging**
