### PR TITLE
Add dependabot

### PR DESCRIPTION
**Pull request by wrt54g**
I added dependabot config for Actions.

### CODE REVIEW

**Comment by mgallien** [comment]
@wrt54g thanks for your contribution !

please have a look at the failing DCO check ?
if you click on details, there is a good explanation of what to do to fix it

**Comment by wrt54g** [comment]
@mgallien How do I sign off in github web?

**Comment by mgallien** [comment]
> @mgallien How do I sign off in github web?

you should include the following line in commit message (should be possible I guess from web UI)

> Signed-off-by: Author Name <authoremail@example.com>

please substitute the appropriate values

**Comment by wrt54g** [comment]
It's not possible to edit commit messages in GitHub web.

**Comment by mgallien** [comment]
> It's not possible to edit commit messages in GitHub web.

I hope you can still do it by maybe starting from scratch
we cannot really help because we cannot write to your personal clone
that would still be a very nice contribution

**Pull request closed without merging**
