### PR TITLE
Build for Debian Bookworm

### PR DESCRIPTION
**Pull request by ivaradi**
Debian Bookworm has been recently released and this commit adds it to the automatic build targets.

### CODE REVIEW

**Review by mgallien — APPROVED** [review]

**Review by claucambra — APPROVED** [review]

**Comment by ivaradi** [comment]
@mgallien and @claucambra thanks for the approvals, but SonarCloud fails, so I cannot merge the PR. Could you, please, help with that?

**Comment by mgallien** [comment]
@ivaradi sorry for the failure with SonarCloud, I have still to figure out a solution for PRs coming from external repositories

**Comment by ivaradi** [comment]
> @ivaradi sorry for the failure with SonarCloud, I have still to figure out a solution for PRs coming from external repositories

Thanks for merging. So SonarCloud would work, if I created branches in this repository? I can do that...

**Pull request merged**
