### PR TITLE
remove some frames in group of settings to simplify layouts

### PR DESCRIPTION
**Pull request by mgallien**
on Windows
Windows native widget style
before
image

### CODE REVIEW

**Comment by mgallien** [comment]
regarding design feedback, I am unsure who I should put as reviewers
I am now testing on Linux KDE Plasma desktop
will ask Camila or Claudio for macOS feedback
I am waiting for feedback before making changes in all settings pages (or not)

**Review by jancborchardt — APPROVED** [review]
Nice, looks much more modern.
A detail, but why is there so much additional whitespace below the options in each of the sections, can that be removed?

(I don't mean the big whitespace between the sections and the bottom, I know that's there to keep the height consistent. :)

**Comment by mgallien** [comment]
on KDE Plasma 6 with default theme
image

I am wondering if we have a way to let the section titles be identified more easily
I am really unsure

**Comment by mgallien** [comment]
last state on Windows
Screenshot 2024-08-28 171954

**Comment by mgallien** [comment]
last state
hopefully better
Screenshot 2024-08-28 220920
Screenshot 2024-08-28 220811

dark mode
Screenshot 2024-08-28 221037
Screenshot 2024-08-28 221021

**Comment by mgallien** [comment]
the label with the desktop client name and release is now left aligned as it should have been
so please ignore this in the screenshots

**Comment by claucambra** [comment]
On macOS the result is less positive

After changes:
Screenshot 2024-08-29 at 13 40 21

Before changes:
Screenshot 2024-08-29 at 13 40 40

**Comment by mgallien** [comment]
updated windows screenshots
Screenshot 2024-08-29 114455
Screenshot 2024-08-29 114245
Screenshot 2024-08-29 114217

**Review by jancborchardt — COMMENTED** [review]
It does look different – and it does look a few steps closer to more native when checking @AndyScherzinger’s screenshots.

On Mac OS it also needs to keep staying natively, or at least not move back, as @claucambra mentioned.

There often seem to be some alignment issues like different amount of whitespace between checkbox lines (first 3 in General → Advanced vs the other ones), and also the aforementioned whitespace inside the bottom of the proxy and bandwidth boxes.

**Comment by AndyScherzinger** [comment]
TO add to Jan's comment, centered headlines are also uncommon on Windows' settings UIs. Things are generally start aligned

**Comment by jancborchardt** [comment]
> To add to Jan's comment, centered headlines are also uncommon on Windows' settings UIs. Things are generally start aligned

Totally agree, also generally design-wise they look a bit lost when centered, best to keep them left-aligned in any case.

**Review by marcoambrosini — APPROVED** [review]

**Comment by mgallien** [comment]
too much issues in this PR
not sure what to do
maybe close and start again from scratch

**Pull request closed without merging**
