### PR TITLE
Use default member init when applicable

### PR DESCRIPTION
**Pull request by er-vin**
This also fixes a couple of warnings at places (out of order init for
instance) and a potential bug in the webflow credentials / qtkeychain
integration.

Signed-off-by: Kevin Ottens <kevin.ottens@nextcloud.com>

### CODE REVIEW

**Comment by sbeyer** [comment]
I wonder that you touch code under `3rdparty`. Is that intentional?

**Comment by er-vin** [comment]
> I wonder that you touch code under `3rdparty`. Is that intentional?

Yes, because as far as I know there's no effort in updating this code. Seems like very old copies so I think we can almost consider them like non 3rdparty code at that point. I could be wrong of course but the ones not in submodule look like soft forks to me.

**Pull request merged**
