### PR TITLE
Fix typos.

### PR DESCRIPTION
**Pull request by hefee**
Debian has a list of known typos in their checking tools.

### CODE REVIEW

**Comment by misch7** [comment]
> The backport to stable-2.6 failed. Please do this backport manually.

Oh yeah, of course 🙈

**Comment by hefee** [comment]
> @hefee Thank you for your contribution! tada +1
> 
> Regarding the `sqlite3` typos: Perhaps you'd like to contribute them also directly to the SQLite project? 

Nope - I don't know what version you copied from were, so please do this yourself.

**Comment by hefee** [comment]
@misch7 whoo you were really fast merging this.

**Pull request merged**
