### PR TITLE
Fixes #533: Removes the copy activities/notifications button

### LINKED ISSUE #533: Activity v2 dialog
Some thoughts about the new activity dialog:

- A lot of free space around the copy button. Are there any hidden elements? Looks really strange now. And it´s way bigger than the close button.
- After copying sth. the copy button reacts really strange while hovering (see screenshot).

activity

### PR DESCRIPTION
**Pull request by camilasan**
- Minor changes: removes white background and changes frame style to the
same used in the accountsettings for consistency.

copy

### CODE REVIEW

**Comment by camilasan** [comment]
@jancborchardt I think we can. Please open an issue for that ;)

**Comment by juliushaertl** [comment]
I'd vote to just remove the button then, since copying the whole activity log into the clipboard is not something that should be that important in the UI.

**Comment by jancborchardt** [comment]
Issue opened at https://github.com/nextcloud/desktop/issues/557 :)

**Comment by jancborchardt** [comment]
Yup, and agree with @juliushaertl that the button can be removed then.

**Pull request merged**
