### PR TITLE
Bugfix/vfs toggle fix

### PR DESCRIPTION
**Pull request by allexzander**

### CODE REVIEW

**Comment by mgallien** [comment]
@allexzander how can I test ?

**Comment by allexzander** [comment]
> Reference in new
@mgallien 
the one for invalid folder alias (01 instead of 1 and 02 instead of 2) can't be tested as it is not reproducible on my end, what I did is, put a fake code that always executes and does what was in that line - the concatenation indeed results into 01 and 02 as those are 2 strings and not integers so string concatenation instead of integer arithmetic happens, so it is fixed by using proper types (2 ints and then casting the result to string)

the second part - you can test by switching to and from VFS mode, in the .cfg file, folders will toggle between Folders and FoldersWithPlaceholders

**Review by claucambra — APPROVED** [review]

**Pull request merged**
