### PR TITLE
Enable multi processor compilation on windows

### PR DESCRIPTION
**Pull request by Dimon4eg**
On my core i7 (4 cores) build times on Windows are following:

Type | Build time, hh:mm:ss
--- | ---
No /MP | 00:04:07
With /MP | 00:01:22

So improvement is 3x 🚀

### CODE REVIEW

**Comment by FlexW** [comment]
In my opinion that shouldn't be done in the scripts. It's rather something you specify on the command line :)

**Comment by Dimon4eg** [comment]
I can add option for that and enable it by default

**Comment by mgallien** [comment]
> I can add option for that and enable it by default

In fact, I do not like what I read in the documentation of this option (the output would intermix and be garbled). It is stated to be able to be slower with it than without it in some cases.

On Windows I use `CMake` with the `ninja` generator. Did you try that ? This is already quite fast and supported by Visual Studio for example.

**Comment by Dimon4eg** [comment]
Why do you use ninja on Windows and not Visual Studio?
In your readme Visual Studio is used:
```
$ cmake -G "Visual Studio 15 2017 Win64" .. -DCMAKE_INSTALL_PREFIX=$USERPROFILE\nextcloud-desktop-client -DCMAKE_BUILD_TYPE=Debug
$ cmake --build . --config Debug --target install
```

**Comment by mgallien** [comment]
> Why do you use ninja on Windows and not Visual Studio?
> In your readme Visual Studio is used:
> 
> ```
> $ cmake -G "Visual Studio 15 2017 Win64" .. -DCMAKE_INSTALL_PREFIX=$USERPROFILE\nextcloud-desktop-client -DCMAKE_BUILD_TYPE=Debug
> $ cmake --build . --config Debug --target install
> ```

Did you try `cmake+ninja+visual studio` ? This is already quite fast and supported by default by Visual Studio for example.

**Comment by Dimon4eg** [comment]
Tried this:
```
$ "c:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x64
$ cmake .. -G Ninja -DCMAKE_INSTALL_PREFIX=nextcloud-desktop-client -DCMAKE_BUILD_TYPE=Debug -DOPENSSL_ROOT_DIR="c:\Program Files\OpenSSL-Win64" -DZLIB_INCLUDE_DIR="d:\dev\libs\zlib-X64-release\include" -DZLIB_LIBRARY="d:\dev\libs\zlib-X64-release\lib\zlib.lib" -DBUILD_TESTING=OFF
-- The C compiler identification is MSVC 19.0.24245.0
-- The CXX compiler identification is MSVC 19.0.24245.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe - broken
CMake Error at C:/Program Files/CMake/share/cmake-3.20/Modules/CMakeTestCCompiler.cmake:66 (message):
  The C compiler

    "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: D:/dev/sk/NextCloud/nextcloud_desktop_fork/build_ninja/CMakeFiles/CMakeTmp

    Run Build Command(s):D:/apps/_tools_/ninja.exe cmTC_133bf && [1/2] Building C object CMakeFiles\cmTC_133bf.dir\testCCompiler.c.obj
    [2/2] Linking C executable cmTC_133bf.exe
    FAILED: cmTC_133bf.exe
    cmd.exe /C "cd . && "C:\Program Files\CMake\bin\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\cmTC_133bf.dir --rc=rc --mt=CMAKE_MT-NOTFOUND --manifests  -- C:\PROGRA~2\MICROS~1.0\VC\bin\amd64\link.exe /nologo CMakeFiles\cmTC_133bf.dir\testCCompiler.c.obj  /out:cmTC_133bf.exe /implib:cmTC_133bf.lib /pdb:cmTC_133bf.pdb /version:0.0 /machine:x64  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
    RC Pass 1: command "rc /fo CMakeFiles\cmTC_133bf.dir/manifest.res CMakeFiles\cmTC_133bf.dir/manifest.rc" failed (exit code 0) with the following output:
    The system cannot find the file specified
    ninja: build stopped: subcommand failed.





  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:4 (project)
```
  
```

How do you use `cmake+ninja+visual studio` ?

**Comment by Dimon4eg** [comment]
According to https://docs.microsoft.com/en-us/cpp/overview/what-s-new-for-visual-cpp-in-visual-studio?view=msvc-160

> You can now use Ninja (a build system that evaluates incremental builds very quickly) to improve incremental build times for MSBuild-based Linux projects. You can opt into this feature by setting "Enable Incremental Build" to "With Ninja" in the General Property Page. Ninja (ninja-build) must be installed on your remote Linux system or WSL.

It supports it only for Linux.

**Comment by FlexW** [comment]
> 
> 
> According to https://docs.microsoft.com/en-us/cpp/overview/what-s-new-for-visual-cpp-in-visual-studio?view=msvc-160
> 
> > You can now use Ninja (a build system that evaluates incremental builds very quickly) to improve incremental build times for MSBuild-based Linux projects. You can opt into this feature by setting "Enable Incremental Build" to "With Ninja" in the General Property Page. Ninja (ninja-build) must be installed on your remote Linux system or WSL.
> 
> VS supports it only for Linux.

It's also supported with CMake and regular Windows applications. See here https://docs.microsoft.com/en-us/cpp/build/cmake-projects-in-visual-studio?view=msvc-160 . If you have Ninja installed, Visual Studio will even pick it up per default. Just open the project in Visual Studio as folder. Visual Studio will take care of everything.

**Comment by Dimon4eg** [comment]
Did know that side of VS. Thanks @FlexW 
Now it builds as fast as VS with `/MP`

**Comment by FlexW** [comment]
@Dimon4eg Glad, it worked out for you :) I guess we can close that pr then?

**Comment by Dimon4eg** [comment]
This still can be useful for people who follow your readme on Windows. Expect anyone will be surprised during build that VS uses only one core.

**Comment by FlexW** [comment]
> This still can be useful for people who follow your readme on Windows. Expect anyone will be surprised during build that VS uses only one core.

Then we should rather fix the readme. As @mgallien noted, that option can even harm the compilation.

**Comment by Dimon4eg** [comment]
Currently it works good. Later you can switch it off if encountered an issue.

**Comment by mgallien** [comment]
> > This still can be useful for people who follow your readme on Windows. Expect anyone will be surprised during build that VS uses only one core.
> 
> Then we should rather fix the readme. As @mgallien noted, that option can even harm the compilation.

Let's update the documentation. This is also the new recommended way from Microsoft.

**Comment by mgallien** [comment]
> > > This still can be useful for people who follow your readme on Windows. Expect anyone will be surprised during build that VS uses only one core.
> > 
> > 
> > Then we should rather fix the readme. As @mgallien noted, that option can even harm the compilation.
> 
> Let's update the documentation. This is also the new recommended way from Microsoft.

And by the way, please keep contributing even if some changes are not always merged

**Pull request closed without merging**
