### PR TITLE
Introduce an about dialog

### PR DESCRIPTION
**Pull request by camilasan**
Every proper application has that!

For decreasing window height in #6075

....

@jancborchardt: you can access the 'about' in the menu in the system tray. Their version removes the about text in settings but I kept it when I was merging the changes:

aboutdialog

menuabout

### CODE REVIEW

**Comment by splitt3r** [comment]
Perhaps merge the dialog with the legal one? Seems realted to me + the other one looks not really ready.

**Comment by jancborchardt** [comment]
I'm not a fan of splitting up the dialogs. We should have as few pieces of interface as possible:
- Tray menu
- Settings dialog
- Sharing dialog

This "About" section is currently in the "General" tab of the settings dialog. If that's too much, we can simply cut the text. But we should not add yet another entry in the tray menu which is too long already. :)

**Comment by jancborchardt** [comment]
@camilasan the "About" is still in the "General" tab right now, and I’d say for now that’s fine. We could look at it again when we are done with other UI stuff? :)

**Comment by er-vin** [comment]
Ping @jancborchardt now that we got the new GUI and that the context menu is super short (but not accessible on Mac), should we reevaluate this?

**Comment by jancborchardt** [comment]
I'd say what I said before still makes sense. The info is fine in the "General" tab of the settings window, and there's no reason to add a direct link to this in the tray dialog nor right-click menu of it.

**Comment by er-vin** [comment]
Alright then, @camilasan should we close this then?

**Pull request closed without merging**
