### PR TITLE
VFS. Allow dehydartion of readonly files. Preserve 'readonly' flag when creating a placeholder.

### PR DESCRIPTION
**Pull request by allexzander**
Signed-off-by: allexzander <blackslayer4@gmail.com>

This fixes https://github.com/nextcloud/desktop/issues/3156

### CODE REVIEW

**Review by mgallien — CHANGES_REQUESTED** [review]
You have a typo in the commit message

**Comment by allexzander** [comment]
@mgallien Fixed

**Review by mgallien — APPROVED** [review]

**Pull request merged**
