### PR TITLE
send OS name and version to auto updater to allow selective upgrades

### PR DESCRIPTION
**Pull request by mgallien**
in order to be able to suuport legacy OS, also sends the OS name and
version

will be used to detect Windows 8.1 and similar legacy versions

Signed-off-by: Matthieu Gallien <matthieu_gallien@yahoo.fr>

### CODE REVIEW

**Comment by mgallien** [comment]
Related to [detect some legacy Windows versions and return legacy update version](https://github.com/nextcloud/client_updater_server/pull/54)

**Comment by allexzander** [comment]
@mgallien Which of those 3 contain Windows Build Number? Like, for CfAPI we need Windows 10 Build Number 1709. I've been checking what the kernel and product version functions return, but, couldn't find a build number in any of those. So, I am wondering, if we need a platform-specific "winBuildNumber" here.

**Review by allexzander — APPROVED** [review]

**Comment by mgallien** [comment]
> @mgallien Which of those 3 contain Windows Build Number? Like, for CfAPI we need Windows 10 Build Number 1709. I've been checking what the kernel and product version functions return, but, couldn't find a build number in any of those. So, I am wondering, if we need a platform-specific "winBuildNumber" here.

The kernel version on Windows is 1 to 1 mapping to the Windows 10 versions. We will be able to get data needed to know if CfApi is supported.

**Pull request merged**
