### PR TITLE
Fix for #1382 "linux client crashes for no discernable reason"

### PR DESCRIPTION
**Pull request by mawasak**
There in no "return" in
PropagateUploadFileCommon::slotStartUpload in if (prevModtime != _item-
>_modtime) {... }

There is possibility that
PropagateItemJob::done(status, errorString)
maybe called two times from PropagateUploadFileCommon::slotStartUpload
1. in if (prevModtime != _item->_modtime) {... }
2. in if (fileIsStillChanging(*_item)) {..}
if changes in files are frequent the second call is possible.

This two calls has effect in PropagatorCompositeJob::slotSubJobFinished
and job is removed two times in _runningJobs.remove(i);
(the second time with argumetnt -1 (because first call removed job).

This return was removed in commit
efc039863b096f0e39543001b6cb53937808bebf - by accident I think.

Good simulation is to synchronize firefox profile with frequent page
refresh.

### CODE REVIEW

**Comment by DominiqueFuchs** [comment]
Hey @mawasak , thanks a lot for the catch! I'm not sure on this one - but from the comments I guess the intention of this if statement may be to request another upload but indeed continue on this one (e.g. no return from the if).

If this is the case, a modification of the the if statement may be more logically correct **and** prevent illegal duplication of job removals:
`if ( (prevModtime != _item->_modtime) && !(fileIsStillChanging(*_item)) )`

Maybe @misch7 finds some time to comment on this.

**Comment by mawasak** [comment]
Hi, 
@DominiqueFuchs  intention for this two if statements is to react on modification time and change in file size before sync I guess.
So maybe it should  be something as:
`if ( (prevModtime != _item->_modtime) || (fileIsStillChanging(*_item)) )`

the code in if statement is the same in both cases (difference is in error message).
During my tests I get in log file (without return in first if statement, with Debug build):
`
[OCC::PropagatorCompositeJob::slotSubJobFinished        ASSERT: "i >= 0" in file /home/XXXX/src/libsync/owncloudpropagator.cpp, line 835
`

**Comment by DominiqueFuchs** [comment]
@mawasak This is exactly what I mean: They are **not** the same if the first one (intentionally) does not return but continue and schedule a second upload and the second also schedules another upload _but_ (see code comment) skips this current upload because it‘s changing **right now**, so it upload makes no sense. This behaviour would make sense to me, but as already mentioned, I‘m not totally sure if this was really the intention. My proposed if-condition in my previous comment should prevent the error you‘re mentioning because it logically eliminates the possibility that the following if statement is also true (thus further decreasing the queue).

**Comment by mawasak** [comment]
@DominiqueFuchs  ....so  we are waiting on review:)

**Comment by DominiqueFuchs** [comment]
Thanks @camilasan for reviewing this - I guess then it was really a simple mistake by the referenced commit and I misunderstood the code comments from the initial dev of this part. Thanks again @mawasak for contributing! I‘ll merge this after the CI build. ☺️

**Pull request merged**
