### PR TITLE
Updater: Enhance UI, make build optional

### PR DESCRIPTION
**Pull request by misch7**
Screenshot from 2020-03-09 04-23-39

### UI: Implement auto-update option and update button

- Add checkbox and button to UI
- Add new parameter autoUpdateCheck to ConfigFile

### Bugfix
- Fix OCUpdater: Also change status on network error or invalid XML

### Add _CMake_ option `BUILD_UPDATER` to make the updater optional

- Default: `BUILD_UPDATER` = `NO`

  To ease builds for distro packages and contributors (regardless of the specified update URL)

- Enable updater build for Drone CI and AppImage builds

### Next steps (follow-up PRs)

- Resurrect auto-update functionality (macOS (Sparkle) work in progress, Windows next)
- Add support for update channels: stable, beta

### CODE REVIEW

**Comment by misch7** [comment]
🍒 Cherry-picked to stable-2.6

**Comment by jancborchardt** [comment]
Good stuff! :) Since it both deals with the version/updates, the "Updates" section could eventually be rolled into the "About" part where it shows the version. Something like:

> Version [2.6.3](https://docs.nextcloud.com/desktop/2.6/). **Update to 2.6.4 available: [ [Download](https://download.nextcloud.com/desktop/releases/Linux/Nextcloud-2.6.4-x86_64.AppImage) ]**
> [x] Automatically check for updates **[ Check now ]**

With "Download" being a button. And when you are up to date:

> Version [2.6.4](https://docs.nextcloud.com/desktop/2.6/), up to date.
> [x] Automatically check for updates **[ Check now ]**

Also shortened the text, and the "Check now" button should be closer to the text – just like above with the "Ask for confirmation before syncing folders larger than …" and the input box. :)

**Comment by jonasgarstick** [comment]
So is this enhancement gone again? (can only speak for macOS)

nc-update-download
notification

**Comment by FlexW** [comment]
@jonasgarstick The one in the notification is expected because macOS does not allow to embed links in notifications. For the settings menu I'm not sure. Could you file an issue about it?

**Comment by jonasgarstick** [comment]
Thanks for your comment @FlexW → #3254

**Pull request merged**
