### PR TITLE
Update sharedialog.cpp

### PR DESCRIPTION
**Pull request by castillo92**
The original sentence uses the word "share" three times and is too redundant when translated into other languages

### CODE REVIEW

**Comment by FlexW** [comment]
Looks good. Could you give your commit a more meaningful commit message and sign it off to please the DCO bot? If you don't know how to do it (Maybe adjust the commit message to something more meaningful):
```
git commit --amend --signoff -m "l10n: Remove redundant share words"
git push --force-with-lease origin patch-1
```

**Comment by castillo92** [comment]
> 
> 
> Looks good. Could you give your commit a more meaningful commit message and sign it off, to please the DCO bot? If you don't know how to do it (Maybe adjust the commit message to something more meaningful):
> 
> ```
> git commit --amend --signoff -m "l10n: Remove redundant share words"
> git push --force-with-lease origin patch-1
> ```

Excuse me, but I created this PR using GitHub Web, where can I execute the commands?

**Review by rakekniven — APPROVED** [review]

**Comment by rakekniven** [comment]
> Excuse me, but I created this PR using GitHub Web

Nextime just the following before you commit:

Signed-off-by: yourgithubusername <youremailadressusedatgithub@example.com>

Using the webinterface most time as well.

**Comment by castillo92** [comment]
> > Excuse me, but I created this PR using GitHub Web
> 
> Nextime just the following before you commit:
> 
> Signed-off-by: yourgithubusername [youremailadressusedatgithub@example.com](mailto:youremailadressusedatgithub@example.com)
> 
> Using the webinterface most time as well.

I do not understand very well whats happend.
One month ago I signed something similar to DCO. Githb sent me an email... 
Where should I write...?
`Signed-off-by: yourgithubusername youremailadressusedatgithub@example.com`

Should I close this PR?

**Comment by rakekniven** [comment]
> Should I close this PR?

No, I merged it right now.

My english wasn't very good, sorry. See how I sign my commits within GitHub web UI here:
https://github.com/nextcloud/docker-ci/pull/267/commits/030f16f405062cc2f39836fcf534565e63f3bffe

**Pull request merged**
