### PR TITLE
Logo update

### PR DESCRIPTION
**Pull request by DominiqueFuchs**
Added png exports of current logo from [promo](https://github.com/nextcloud/promo) branch as preparation for subsequent changes to implement the new variant in shell implementations, build chains and packaging.

As a proposal I decided to add them besides the old one for this reason until all changes are complete. I this gets acknowledged, I'll work on implementing these files in the corresponding places.

### CODE REVIEW

**Comment by DominiqueFuchs** [comment]
See also #22 and #810

**Comment by DominiqueFuchs** [comment]
Completed AFAICT for the windows buildchain & package. See pictures:
EXE
QuickAccess
SyncFolder

There are a few notable changes besides the known new files in the corresponding commit:

- Also updated sidebar-icons for macOS
- Updated AddAppIconMacro to also reflect new resolutions (including macOS)
- Updated ECMAddAppIcon based on current version in [KDE repo](https://github.com/KDE/extra-cmake-modules/blob/master/modules/ECMAddAppIcon.cmake) with modification to our buildflow. Included simplifications to png2ico execute_custom_command and arguments assuming png2imagemagick is present. See comment in code. Doesn't change anything to the current situation regarding this limitation. Also updated mac-image-gathering based on current guidelines by Apple. This may as well fix some retina issues as the old state was pretty outdated (in terms of used resolutions and assignments) and I saw some issue here about this a while ago.

Will report back here when I checked build and package on macOS & KDE.

**Comment by jancborchardt** [comment]
What do you think @camilasan @juliushaertl @misch7?

**Comment by misch7** [comment]
I think it's great! :-)

Works for me on Windows 👍 

On my local Mac build the icons got placed in `nextcloud.app > Contents > Resources > final_src.icns` instead of `Nextcloud.icns` so I've got to try it on our build servers to be sure ;)

**Comment by DominiqueFuchs** [comment]
Alright, just saw that it blows up on the drone instances, except for the debian build - strange. Output looks like the new image files were not found e.g. an empty arg call was done within the macro module.
I'll look into this.
Thanks for the comments & invite btw!

**Comment by misch7** [comment]
You're welcome! =) 😸 

If it helps, here's the output I got from calling:

```
$ git apply --check 1401.patch
error: theme/colored/nc_logo_rnd_nb_1024px.png: No such file or directory
error: theme/colored/nc_logo_rnd_nb_10px.png: No such file or directory
error: theme/colored/nc_logo_rnd_nb_128px.png: No such file or directory
error: theme/colored/nc_logo_rnd_nb_16px.png: No such file or directory
error: theme/colored/nc_logo_rnd_nb_24px.png: No such file or directory
error: theme/colored/nc_logo_rnd_nb_256px.png: No such file or directory
error: theme/colored/nc_logo_rnd_nb_32px.png: No such file or directory
error: theme/colored/nc_logo_rnd_nb_40px.png: No such file or directory
error: theme/colored/nc_logo_rnd_nb_48px.png: No such file or directory
error: theme/colored/nc_logo_rnd_nb_512px.png: No such file or directory
error: theme/colored/nc_logo_rnd_nb_64px.png: No such file or directory
error: theme/colored/nextcloud-icon-10px.png: No such file or directory
error: theme/colored/nextcloud-icon-16px.png: No such file or directory
error: theme/colored/nextcloud-icon-40.png: No such file or directory
error: theme/colored/nextcloud-icon-1024.png: No such file or directory
error: theme/colored/nextcloud-icon-128.png: No such file or directory
error: theme/colored/nextcloud-sidebar-128.png: No such file or directory
error: theme/colored/nextcloud-icon-16.png: No such file or directory
error: theme/colored/nextcloud-sidebar-16.png: No such file or directory
error: theme/colored/nextcloud-icon-24.png: No such file or directory
error: theme/colored/nextcloud-icon-256.png: No such file or directory
error: theme/colored/nextcloud-sidebar-256.png: No such file or directory
error: theme/colored/nextcloud-icon-32.png: No such file or directory
error: theme/colored/nextcloud-sidebar-32.png: No such file or directory
error: theme/colored/nextcloud-icon-48.png: No such file or directory
error: theme/colored/nextcloud-icon-512.png: No such file or directory
error: theme/colored/nextcloud-icon-64.png: No such file or directory
error: theme/colored/nextcloud-sidebar-64.png: No such file or directory

```

**Comment by DominiqueFuchs** [comment]
Got it. There were to related mistakes that led to linux (CI fail) and mac issues (wrong named icon pack in build output). I had to update a variable in the CMakeLists in /src/gui [7aefa5a](https://github.com/nextcloud/desktop/pull/1401/commits/7aefa5afafd31f891f857a358d864ef32f7b439b) that changed in the new ECMAddAppIconScript.

For the linux builds, I initially didn't realized possible case issues when adding the new logo files. But linux is indeed case sensitive in most (no pun intended) cases. Fixed by applying consistent naming and theme packaging [e2f7947](https://github.com/nextcloud/desktop/pull/1401/commits/e2f7947966158b34d94f470363bfbd78dd6361c6) and [6f5dcf](https://github.com/nextcloud/desktop/pull/1401/commits/6f5dcfa78b5ba4ec8bab209a473af316a6758a66)

Mac and linux builds worked now fine on my end. Ready to merge when you are 🦊 ☺️

**Pull request merged**
