### PR TITLE
fixed detection of server version in cmd client similar to gui client (2nd try, signed off)

### PR DESCRIPTION
**Pull request by errror**
first check status.php for version and then capabilities, only use version string if not empty

this also fixes 'File names containing the character ":" are not supported on this file system.' errors in nextcloudcmd (on Linux): The invalidFilenameRegex was set to a static default in case the server version was not set correctly. As newer versions of nextcloud do not return the version in capabilities but status.php, the server version was empty.

As I did not find a way to fullfil your requirements in my first PR, I created a new one. This one has a commit message with a correct Signed-off line. It also has no other changes as I did not enable the actions in this fork.

### CODE REVIEW

**Review by claucambra — APPROVED** [review]

**Comment by claucambra** [comment]
Thanks for the changes!

**Review by claucambra — CHANGES_REQUESTED** [review]
In updating the branch you have added a merge commit -- please don't update the contents of the PR with the "Update branch" button as this adds merge commits to your pull request

Once you have removed the merge commit, we will be able to merge

**Comment by errror** [comment]
> In updating the branch you have added a merge commit -- please don't update the contents of the PR with the "Update branch" button as this adds merge commits to your pull request
> 

ok, will remember this for the future.

> Once you have removed the merge commit, we will be able to merge

I have removed the merge commit!

**Comment by claucambra** [comment]
> > In updating the branch you have added a merge commit -- please don't update the contents of the PR with the "Update branch" button as this adds merge commits to your pull request
> 
> ok, will remember this for the future.
> 
> > Once you have removed the merge commit, we will be able to merge
> 
> I have removed the merge commit!

Thanks!

One last thing -- the sign-off points to `errror@errror.org` but it seems your commit is in fact authored under the email `pcernko@mpi-klsb.mpg.de`. Could you amend the commit and either A) modify the signed-off-by OR B) modify your author email in the commit?

**Comment by errror** [comment]
> 
> One last thing -- the sign-off points to `errror@errror.org` but it seems your commit is in fact authored under the email `pcernko@mpi-klsb.mpg.de`. Could you amend the commit and either A) modify the signed-off-by OR B) modify your author email in the commit?
> 
> This will allow our CI pipeline to pass and we can merge the PR

I fixed the author of my commit message to match the sign-off.

**Comment by claucambra** [comment]
> > One last thing -- the sign-off points to `errror@errror.org` but it seems your commit is in fact authored under the email `pcernko@mpi-klsb.mpg.de`. Could you amend the commit and either A) modify the signed-off-by OR B) modify your author email in the commit?
> > This will allow our CI pipeline to pass and we can merge the PR
> 
> I fixed the author of my commit message to match the sign-off.

Awesome, thanks!

**Review by claucambra — APPROVED** [review]

**Pull request merged**
