### PR TITLE
Master is now what will become 3.1

### PR DESCRIPTION
**Pull request by er-vin**
Signed-off-by: Kevin Ottens <kevin.ottens@nextcloud.com>

### CODE REVIEW

**Comment by ivaradi** [comment]
I have updated the CMake patch for version 3.0.0 (so master will be built in its present state) and created Debian branches for the stable-3.0 branch as well (with the same content as the branches for master). Once this PR gets merged, I will update the master branches for 3.1.0.

BTW, I noticed that there is a tag v3.0.0 (and a draft release as well). Does this mean that a stable 3.0.0 release has been created or is it still going to be worked on?

**Comment by er-vin** [comment]
> BTW, I noticed that there is a tag v3.0.0 (and a draft release as well). Does this mean that a stable 3.0.0 release has been created or is it still going to be worked on?

Yes, it's getting ready for publication.

**Comment by ivaradi** [comment]
I see, however tagging early can cause problems for the Debian build script, because the it identifies a stable release by the commit having a stable version tag, like v3.0.0. So either we should find a new way to identify the release commits or we should not tag early.

**Comment by er-vin** [comment]
> I see, however tagging early can cause problems for the Debian build script, because the it identifies a stable release by the commit having a stable version tag, like v3.0.0. So either we should find a new way to identify the release commits or we should not tag early.

I don't think moving from tag + binary produced to publication should be automated. You might want to keep release binaries under wraps until they're announced. So indeed you might want a way to declare "this release is published".

**Pull request merged**
