### PR TITLE
use an en-dash for the userstatus panel

### PR DESCRIPTION
**Pull request by szaimen**
Just noticed in https://github.com/nextcloud/desktop/pull/4624

Signed-off-by: szaimen <szaimen@e.mail.de>

### CODE REVIEW

**Review by claucambra — APPROVED** [review]
Looks good!

**Comment by szaimen** [comment]
BTW: @jancborchardt I wonder if we should add some more words to the clear status as I don't find it very clear what the second part menas. Here a small mockup (sorry for the red)!
image

**Comment by szaimen** [comment]
> BTW: @jancborchardt I wonder if we should add some more words to the clear status as I don't find it very clear what the second part menas. Here a small mockup (sorry for the red)! image

Lets do this in a follow-up. Please merge if the change is fine :)

**Comment by szaimen** [comment]
Please merge if the change is fine :)

**Review by jancborchardt — CHANGES_REQUESTED** [review]
We do not use em dashes anywhere, but **en**. :) `–`
So either we should use that, or maybe even the nicer middle dot which we often use: `·`

**Comment by szaimen** [comment]
> We do not use em dashes anywhere, but **en**. :) `–`

Sorry I confused the name of them. The en dash id already applied in this PR :)

**Comment by jancborchardt** [comment]
@szaimen I did copy it earlier to check but it didn't seem like it was, it was actually an em dash?

**Comment by szaimen** [comment]
> We do not use em dashes anywhere, but **en**. :) `–`

Hm... Isn't this an en dash? Can you paste an en dash here? I will use it here then...

**Comment by jancborchardt** [comment]
Yes, as pasted above: –

**Review by jancborchardt — APPROVED** [review]
Nice – very! :D

**Comment by szaimen** [comment]
Thanks! :)

**Comment by szaimen** [comment]
@claucambra @mgallien what is needed for merging this? :)

**Pull request merged**
