### PR TITLE
add scrollbars on small screen when seting up sync and sync directory

### PR DESCRIPTION
**Pull request by mgallien**
to fix problem reported by customer

### CODE REVIEW

**Review by allexzander — APPROVED** [review]

**Comment by FlexW** [comment]
@mgallien If I test your pr, I get scroll bars even if my screen has enough space. I think this needs improvements.

https://user-images.githubusercontent.com/19961516/118514469-dc788380-b734-11eb-8813-35f90f8aa15e.mp4

**Comment by mgallien** [comment]
> @mgallien If I test your pr, I get scroll bars even if my screen has enough space. I think this needs improvements.
> wizard-issues-2021-05-17_17.23.55.mp4

there is a quite big empty part in the bottom

I can probably squeeze part of it to limit this

did this design got done by Jan or just by someone from the desktop team ?

**Comment by FlexW** [comment]
> > @mgallien If I test your pr, I get scroll bars even if my screen has enough space. I think this needs improvements.
> > wizard-issues-2021-05-17_17.23.55.mp4
> 
> there is a quite big empty part in the bottom
> 
> I can probably squeeze part of it to limit this
> 
> did this design got done by Jan or just by someone from the desktop team ?

Jan and me ;) The part is empty because that is the area where radio buttons are shown if the local folder is not empty. It was wished, that the dialog does not change it's layout if these radio buttons get shown. You can toggle these radio buttons if you pick a non empty local folder for synchronisation.

**Comment by FlexW** [comment]
Just one thought from me: I'm not sure if we should add these scroll bars at all. There are other people that use the client via a terminal server, and they don't seem to have these problems. Maybe they can do something on their side that the wizard window opens not scaled that big. I'm just afraid we make the experience worse for every other customer/user, and "fix" it only for them :)

**Pull request closed without merging**
