### PR TITLE
Double-clicking tray icon opens currently-selected user's local folder (if available)

### LINKED ISSUE #1184: Feature Request: Allow double clicking the tray icon to open the 'nextcloud' folder
Dropbox allows double clicking the application's tray icon to open the main sync folder.

I'd love if a similar feature could be implemented in nextcloud.

Single click could still be left as opening the app status/settings, but the double click captured to open the folder.

### PR DESCRIPTION
**Pull request by claucambra**
Closes #1184

Signed-off-by: Claudio Cambra <claudio.cambra@gmail.com>

### CODE REVIEW

**Review by mgallien — COMMENTED** [review]
can you add this to the user documentation ?
without that nobody will ever discover this hidden feature
I would have never known that systray icon can behave differently when double clicked

**Comment by claucambra** [comment]
> can you add this to the user documentation ?
> without that nobody will ever discover this hidden feature
> I would have never known that systray icon can behave differently when double clicked

I added a line saying double-clicking will open the current user's locally synced folder

**Comment by allexzander** [comment]
@claucambra The feature works well, however, I am surprised one of the test cases is in fact broken:
```
FAIL!  : TestFolderWatcher::testMove3LevelDirWithFile() 'waitForPathChanged(_rootPath + "/a/b/c/empty.txt")' returned FALSE. ()
..\..\..\test\testfolderwatcher.cpp(170) : failure location
```

**Comment by allexzander** [comment]
@claucambra My bad. It happened just 2 times and does not happen to me locally. Looks like random failure in unit tests :(

**Review by allexzander — APPROVED** [review]

**Comment by claucambra** [comment]
> @claucambra The feature works well, however, I am surprised one of the test cases is in fact broken:
> 
> ```
> FAIL!  : TestFolderWatcher::testMove3LevelDirWithFile() 'waitForPathChanged(_rootPath + "/a/b/c/empty.txt")' returned FALSE. ()
> ..\..\..\test\testfolderwatcher.cpp(170) : failure location
> ```
> 
> Maybe, just try to rebase the branch first, and you might get lucky.

`TestFolderWatcher` seems to fail pretty randomly :(

**Review by mgallien — APPROVED** [review]

**Pull request merged**
