### PR TITLE
Make apps menu scrollable when content taller than available vertical space, preventing borking of layout

### PR DESCRIPTION
**Pull request by claucambra**
Addresses a point in #4432

This PR:

https://user-images.githubusercontent.com/70155116/178548606-bc086e5d-7658-4bc5-ab56-337195e3df84.mov

Before:

Screenshot 2022-07-12 at 18 51 17

### CODE REVIEW

**Review by allexzander — APPROVED** [review]

**Comment by mgallien** [comment]
@claucambra can you ask feedback from designers ?
I am fine with the code but I do not feel comfortable approving the design myself

**Comment by nimishavijay** [comment]
Nice! Looks much better than before! :) Only a few small suggestions:
- [ ] We could increase the max-width of the menu to 30 or even 40% of the dialogue as some items are getting ellipsised
- [ ] Could we add a bit of spacing to the right so that the scrollbar isn't as close to the text? Around 4px space between the end of the text and the starting of the scrollbar will probably do.
- [ ] Move up the menu by like 2px so that it starts where the header ends (so that small gap between the header and menu is closed)

**Comment by claucambra** [comment]
> Nice! Looks much better than before! :) Only a few small suggestions:
> 
> * [ ]  We could increase the max-width of the menu to 30 or even 40% of the dialogue as some items are getting ellipsised
> * [ ]  Could we add a bit of spacing to the right so that the scrollbar isn't as close to the text? Around 4px space between the end of the text and the starting of the scrollbar will probably do.
> * [ ]  Move up the menu by like 2px so that it starts where the header ends (so that small gap between the header and menu is closed)

Regarding the last point, this would be inconsistent with how the user menu appears:

Screenshot 2022-07-22 at 13 51 51

How would you prefer the spacing to be?

**Comment by nimishavijay** [comment]
Ahh okay, good point. I see that there is a couple of pixels of space on the left of the menu as well so it's intentional :) So we can leave it be :)

**Comment by claucambra** [comment]
> Ahh okay, good point. I see that there is a couple of pixels of space on the left of the menu as well so it's intentional :) So we can leave it be :)

Okay 🙂 Here's a revised version:


Uploading Screen Recording 2022-07-22 at 14.13.30.mov…

**Review by nimishavijay — APPROVED** [review]
👌🏽🚀 :)

**Review by mgallien — APPROVED** [review]

**Pull request merged**
