### PR TITLE
Make argument singular to fix i18n issue

### PR DESCRIPTION
**Pull request by rakekniven**
Reported at Transifex.
See https://www.transifex.com/nextcloud/nextcloud/translate/#hu_HU/client/309577611

Signed-off-by: rakekniven <2069590+rakekniven@users.noreply.github.com>

### CODE REVIEW

**Comment by FlexW** [comment]
@rakekniven Could you please also fix the tests that broke because of this change?

**Comment by rakekniven** [comment]
Hello @FlexW I was looking for it but did not found the related test. Searching for "server reported" only brought one result :-( 

Can you point me to the related test. For sure I will try to fix it.

**Comment by FlexW** [comment]
Thanks @rakekniven do you think it is possible for you to squash the commit that fixes the test with the commit that broke the test?

**Comment by rakekniven** [comment]
> Thanks @rakekniven do you think it is possible for you to squash the commit that fixes the test with the commit that broke the test?

Hello @FlexW , I do all my GitHub work using the webinterface of GitHub. AFAIK there is currently no way to squash commits using the web UI. Can you do that? Thank you.

**Review by mgallien — APPROVED** [review]

**Review by FlexW — APPROVED** [review]

**Pull request merged**
