### PR TITLE
CSync Errors cleanup

### PR DESCRIPTION
**Pull request by camilasan**
PR https://github.com/owncloud/client/pull/6384
Issue https://github.com/owncloud/client/issues/6274

### CODE REVIEW

**Comment by juliushaertl** [comment]
@camilasan Build fails for this one :wink: 

```
[ 17%] Building CXX object src/libsync/CMakeFiles/nextcloudsync.dir/discoveryphase.cpp.o
/drone/src/github.com/nextcloud/client/src/libsync/discoveryphase.cpp: In member function 'void OCC::DiscoverySingleDirectoryJob::lsJobFinishedWithoutErrorSlot()':
/drone/src/github.com/nextcloud/client/src/libsync/discoveryphase.cpp:417:17: error: '_error' was not declared in this scope
     } else if (!_error.isEmpty()) {
                 ^
At global scope:
cc1plus: warning: unrecognized command line option '-Wno-gnu-zero-variadic-macro-arguments'
make[2]: *** [src/libsync/CMakeFiles/nextcloudsync.dir/discoveryphase.cpp.o] Error 1
src/libsync/CMakeFiles/nextcloudsync.dir/build.make:230: recipe for target 'src/libsync/CMakeFiles/nextcloudsync.dir/discoveryphase.cpp.o' failed
CMakeFiles/Makefile2:202: recipe for target 'src/libsync/CMakeFiles/nextcloudsync.dir/all' failed
make[1]: *** [src/libsync/CMakeFiles/nextcloudsync.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by camilasan** [comment]
My bad @juliushaertl. This one https://github.com/nextcloud/client/pull/315 needs to be in first.

**Comment by rullzer** [comment]
#315 is in

**Comment by camilasan** [comment]
Rebase done.

**Pull request merged**
