### PR TITLE
rearange CMake find_package OpenSSL

### PR DESCRIPTION
**Pull request by ShinjiLE**
the command seems to be malformed . The keyword VERSION is not valid .
And the version should follow direct after the packagename.

### CODE REVIEW

**Comment by camilasan** [comment]
Issue #526.

**Comment by rullzer** [comment]
@ShinjiLE thnx. It seems this does break CI because now it finally checks properly. Let me try to bump the images later today.

**Comment by camilasan** [comment]
I updated the branch. Can we merge it @rullzer ?

**Comment by rullzer** [comment]
@camilasan nope not yet I need to add the new CI images else they will always fail

**Pull request merged**
