### PR TITLE
Setup wizard: implement an animated and interactive slide show

### PR DESCRIPTION
**Pull request by jpnurmi**

### CODE REVIEW

**Comment by jpnurmi** [comment]
Before:
before

After:
after

**Comment by rullzer** [comment]
Cool stuff @jpnurmi 
I'll try to have a look at the actual code soon!

**Comment by jospoortvliet** [comment]
fancy :tada:

**Comment by rullzer** [comment]
I increased the durations a bit because they were going very fast IMO. But awesome stuff!
Let me merge once CI is green

**Pull request merged**
