### PR TITLE
Start macOS app bundle name with uppercase letter

### PR DESCRIPTION
**Pull request by FlexW**
It's a convention on macOS that app bundle names start with an uppercase
letter. This also aligns the app name with Windows and Linux.

Signed-off-by: Felix Weilbach <felix.weilbach@nextcloud.com>

Fixes https://github.com/nextcloud/desktop/issues/2898
Closes https://github.com/nextcloud/desktop/pull/2945

### CODE REVIEW

**Comment by mgallien** [comment]
can you test how it is behaving when we upgrade from a version without #3404 to a version with it ?

**Comment by FlexW** [comment]
@mgallien I can confirm that works

**Review by mgallien — APPROVED** [review]
> @mgallien I can confirm that it works.

Cool

**Review by camilasan — APPROVED** [review]

**Pull request merged**
