### PR TITLE
[WIP] Fix macOS GUI (Qt 5.12)

### PR DESCRIPTION
**Pull request by misch7**
### Step 1: Remove submodule qtmacgoodies and the MacSettingsDialog class

Reverts back to the SettingsDialog class because of bugs and glitches with more recent Qt versions (Qt 5.12) and with the macOS Dark Mode.

See upstream: https://github.com/owncloud/client/pull/7492

This hopefully fixes issue #1501 and some crashes.

GUI on macOS 10.14 (Mojave):
mac-gui

GUI on macOS 10.13 (High Sierra):
mac-gui03

@jancborchardt This also removes the height auto-resize on switching tabs ;-)
cc @camilasan 

Test build: I created a special daily build, including this PRs code (macOS 10.12+):
https://download.nextcloud.com/desktop/daily/Mac/Installer/Nextcloud-qt5.12.5-2.7.0.20191201daily.pkg

### Next steps:

- Fixing DPI / Font issues
- Dark Mode: changing colors of links and other GUI elements

Targeted issues:
- #1501 
- #1539 
- #1602

### CODE REVIEW

**Comment by jancborchardt** [comment]
> @jancborchardt This also removes the height auto-resize on switching tabs ;-)

Heh, seems good! :+1: :)

**Comment by misch7** [comment]
https://github.com/nextcloud/desktop/pull/1651/commits/3ceda7d21e4a109432474eaad99d227111edde8d:

gui-ssl-01

gui-ssl-02

**Comment by misch7** [comment]
Merged for RC1 of the 2.6.2 release - tested on all platforms.

**Comment by misch7** [comment]
Changes by the last commits:

### Links are now background-aware:
gui-links

Update link for example:
gui-update

### Error messages are now background-aware of their container:
gui-error-dark
gui-error-light

Previous styling:
gui-errors-prev


### Share dialog:
gui-share-dialog

TODO - known issue (macOS):
- The background and font colours in the ShareUserLine widget still stay the same.
- Some other icons like the "more" icon ("...") in the settings dialog have to be adjusted in code.

This PR has been merged so that the current state can be tested in RC1 of the upcoming 2.6.2 release.

Download links for all platforms:
https://github.com/nextcloud/desktop/releases/tag/v2.6.2-rc1

cc @jancborchardt @camilasan  @DominiqueFuchs  :)

**Comment by jancborchardt** [comment]
Good stuff! :) Getting there step by step

**Pull request merged**
