### PR TITLE
Theme/Language

### PR DESCRIPTION
**Pull request by devinoldenburg**
I changed the language file for German and changed the design a bit.
See changelog for more infos.

### CODE REVIEW

**Review by devinoldenburg — COMMENTED** [review]
.

**Review by claucambra — CHANGES_REQUESTED** [review]
Hello, a couple of things:

1. Translation files should be changed via our translation system at Transifex, not directly via the files
2. What is the reasoning behind the style changes? What are the efects of your changes? (could you provide screenshots?)
3. You have deleted some .gitignore files without a clear reason, could you explain why?

**Comment by wfxey** [comment]
> Hello, a couple of things:
> 
> 1. Translation files should be changed via our translation system at Transifex, not directly via the files
> 2. What is the reasoning behind the style changes? What are the efects of your changes? (could you provide screenshots?)
> 3. You have deleted some .gitignore files without a clear reason, could you explain why?

1. I didn't knew it sorry 
2. On Windows in Dark Mode you cant see the difference between the color of the text and the background of the button.
3. I  added them again, my bad that I deleted them. It was automatic by GitHub Dektop

**Comment by wfxey** [comment]
> > * I didn't knew it sorry
> 
> don't worry, thanks for trying <3 This is what we use for translation: https://app.transifex.com/nextcloud/nextcloud/translate/#de/client/328739356
> 
> > * On Windows in Dark Mode you cant see the difference between the color of the text and the background of the button.
> 
> We have a workaround for this by using another theme on Windows: #7270 It is actually bug in Qt 6. The fix will be in 3.14.2 (next week or so).

Oh okay nicee

**Comment by wfxey** [comment]
I will try the Website

**Pull request closed without merging**
