### PR TITLE
Hide share button for deleted files and ignored files in tray activity 

### PR DESCRIPTION
**Pull request by claucambra**
Signed-off-by: Claudio Cambra <claudio.cambra@gmail.com>

This fixes one of the issues brought up by #3660

### CODE REVIEW

**Comment by splitt3r** [comment]
Great work. Does this also work for ignored items?

**Review by mgallien — APPROVED** [review]
congratulations !

**Comment by claucambra** [comment]
> Great work. Does this also work for ignored items?

No, but can add :)

**Comment by claucambra** [comment]
Activity items notifying about ignored items not being synced also have the share button hidden now

**Review by allexzander — APPROVED** [review]

**Pull request merged**
