### PR TITLE
Win tests compilation fix.

### PR DESCRIPTION
**Pull request by allexzander**
Signed-off-by: allexzander <blackslayer4@gmail.com>

Fix for Windows build error of not being able to locate #include <sqlite3.h> in tests.

### CODE REVIEW

**Comment by camilasan** [comment]
You could expand on the commit message with what was the error. Just for later when looking at the git history it will be easy to understand what happened.

**Comment by FlexW** [comment]
If you change PRIVATE to PUBLIC on line 71 and 73 in `src/csync/CMakeLists.txt` it should also work and then sqlite3 will not be included globally. I think that should be the proper fix for that.

**Comment by allexzander** [comment]
> If you change PRIVATE to PUBLIC on line 71 and 73 in `src/csync/CMakeLists.txt` it should also work and then sqlite3 will not be included globally. I think that should be the proper fix for that.

@er-vin @camilasan 

This sounds reasonable. Any objections? Asking, since I am not CMAKE-expert.

**Comment by er-vin** [comment]
I agree with @FlexW this would be a better fix. We should slowly move to those more modern constructs.

**Comment by allexzander** [comment]
Alright then, @er-vin @FlexW @camilasan 

Let's approve + merge it.

**Comment by er-vin** [comment]
@allexzander I'm fine with the content of the commit now, still could you please address @camilasan comment about have a more descriptive commit message? She's right that this kind of things might come in handy.

**Review by er-vin — APPROVED** [review]

**Pull request merged**
