### PR TITLE
Add a 'Sync now' button to the sync status header in the tray window

### LINKED ISSUE #4877: Add start sync button
### Issue description
We are arount 20 Person use Nextcloud for our company documents. We use the Windows Sync Client to sync all our needed files at our hard disk. Sometimes we work together which mean that if someone is ready with the documents, we get feedback via mail or chat to start the work. 

The problem is, that the sync clien didn't synced the files that fast so we have to start the sync process manuall. Which is only possible at the settings window.

### Feature description
An start sync button at the huge notification window would be nice,

Sncy Now

### PR DESCRIPTION
**Pull request by claucambra**
image

Closes #4877

Signed-off-by: Claudio Cambra <claudio.cambra@gmail.com>

### CODE REVIEW

**Comment by claucambra** [comment]
> works well will be very convenient but as an user I would never discover this hidden gem we should have visible on hover feedback

Understood, will add a hover effect

**Comment by claucambra** [comment]
> works well will be very convenient but as an user I would never discover this hidden gem we should have visible on hover feedback

Done, here's a video:

https://user-images.githubusercontent.com/70155116/195402626-edba1870-542c-4a61-a9f9-75cffcb43a8d.mp4

**Comment by jancborchardt** [comment]
Hm, after looking at the video, thinking about it again, with @mgallien’s feedback, and @andreas-kainz’s original issue at https://github.com/nextcloud/desktop/issues/4877, I now agree with the proposal to actually just add a button there. :D 

Should be on the right, saying "Sync now", doesn’t need an icon. And then the whole line does not need a hover state, cause that actually looks a bit off.

The button can be text-only or have a simple border around it (with pill-style radius). What do you think @claucambra?

**Review by mgallien — APPROVED** [review]

**Comment by mgallien** [comment]
@jancborchardt @nimishavijay are you OK with the current state ?

**Comment by andyxheli** [comment]
https://github.com/nextcloud/desktop/issues/4608

**Pull request merged**
