### PR TITLE
fixed detection of server version in cmd client similar to gui client:

### PR DESCRIPTION
**Pull request by errror**
first check status.php for version and then capabilities, only use version string if not empty

this also fixes 'File names containing the character ":" are not supported on this file system.' errors in nextcloudcmd (on Linux): The invalidFilenameRegex was set to a static default in case the server version was not set correctly. As newer versions of nextcloud do not return the version in capabilities but status.php, the server version was empty.

Signed-off-by: Patrick Cernko <errror@errror.org>

### CODE REVIEW

**Review by claucambra — APPROVED** [review]
Awesome, thanks!

**Comment by claucambra** [comment]
Hi, as soon as you remove the merge commit f8650933ee8ff1700024a0eb0a4924c2efe6aef6 we can merge

**Comment by claucambra** [comment]
Also, please make sure your relevant commit is signed off :)

**Comment by errror** [comment]
@claucambra I have no idea, what you are talking about when you say "remove the merge commit f865093". Could you please tell me, what I have to do and where?

Also how do I change my already done commit message? When I did the commit, I was not aware of the "signed off" requirement. Should I do a new fork and make the commit with the required "Signed-Off" signature?

**Comment by claucambra** [comment]
> @claucambra I have no idea, what you are talking about when you say "remove the merge commit [f865093](https://github.com/nextcloud/desktop/commit/f8650933ee8ff1700024a0eb0a4924c2efe6aef6)". Could you please tell me, what I have to do and where?

You should rebase the commit on master and drop the merge commits (there are now two, f865093 and b177af9d4f6094093177d9b607ccfff127a4945d)

> Also how do I change my already done commit message? When I did the commit, I was not aware of the "signed off" requirement. Should I do a new fork and make the commit with the required "Signed-Off" signature?

You should amend the commit with the --sign-off flag

**Review by claucambra — CHANGES_REQUESTED** [review]
Once merge commits are removed, we can merge

**Comment by errror** [comment]
> > @claucambra I have no idea, what you are talking about when you say "remove the merge commit [f865093](https://github.com/nextcloud/desktop/commit/f8650933ee8ff1700024a0eb0a4924c2efe6aef6)". Could you please tell me, what I have to do and where?
> 
> You should rebase the commit on master and drop the merge commits (there are now two, [f865093](https://github.com/nextcloud/desktop/commit/f8650933ee8ff1700024a0eb0a4924c2efe6aef6) and [b177af9](https://github.com/nextcloud/desktop/commit/b177af9d4f6094093177d9b607ccfff127a4945d))
> 
> > Also how do I change my already done commit message? When I did the commit, I was not aware of the "signed off" requirement. Should I do a new fork and make the commit with the required "Signed-Off" signature?
> 
> You should amend the commit with the --sign-off flag

**Comment by errror** [comment]
I have created a new PR to fullfil your requirements: [6023](https://github.com/nextcloud/desktop/pull/6023)

**Pull request closed without merging**
