### PR TITLE
Apply http2 patch from owncloud

### PR DESCRIPTION
**Pull request by Milokita**

### CODE REVIEW

**Comment by camilasan** [comment]
Hi, Could you refer to the original patch @Milokita?

**Comment by camilasan** [comment]
I think this is the issue you are trying to fix #1182, correct?

**Comment by Milokita** [comment]
> 
> 
> Hi, Could you refer to the original patch @Milokita?

The original patch: https://github.com/owncloud/client/commit/677e44dc532ef2035f6dc5b3f45c527f6d1b0be2

**Comment by Milokita** [comment]
> 
> 
> I think this is the issue you are trying to fix #1182, correct?

Yes

**Comment by papjul** [comment]
Why does your patch only modify 2 files while the original OC patch modify 5 files?
I know that 2 files are "only" tests (though I strongly recommend keeping them), but what about src/libsync/propagatedownload.cpp?
@Milokita @camilasan Do you both confirm this works without it and there are no edge cases risks?

**Comment by Milokita** [comment]
As https://github.com/nextcloud/desktop/issues/1182 reports, the situation occurs when **uploading** large files containing umlauts / non-ASCII characters, so I leave the "propagatedownload.cpp" untouch. 

  According to my test, downloading several 7z files which is 50MB containing Chinese, numbers, space, special characters works fine with this new build. The same applies to uploading 7z test files which are 100MB.

@papjul

**Pull request merged**
