### PR TITLE
Mark as single window app

### PR DESCRIPTION
**Pull request by nicolasfella**
There can only be one instace of the client running

Mark it as such in the .desktop file

This allows desktop environments to adjust their UI accordingly

Signed-off-by: Nicolas Fella <nicolas.fella@gmx.de>

### CODE REVIEW

**Review by mgallien — APPROVED** [review]
Thanks a lot !

**Review by allexzander — APPROVED** [review]

**Review by claucambra — APPROVED** [review]

**Comment by mgallien** [comment]
@nicolasfella could you please rebase your PR on latest master such that we can merge it ?

**Comment by mgallien** [comment]
@nicolasfella can you have a look at the AppImage build error ?
looks like the new desktop file entry is supposedly not compliant (at least from this parser point of view :smile: )

**Comment by nicolasfella** [comment]
> @nicolasfella can you have a look at the AppImage build error ? looks like the new desktop file entry is supposedly not compliant (at least from this parser point of view smile )

SingleMainWindow is a very recent addition to the desktop file spec. It looks like the appimage tooling isn't up to date and doesn't account for version 1.5 of the spec

**Comment by mgallien** [comment]
> > @nicolasfella can you have a look at the AppImage build error ? looks like the new desktop file entry is supposedly not compliant (at least from this parser point of view smile )
> 
> SingleMainWindow is a very recent addition to the desktop file spec. It looks like the appimage tooling isn't up to date and doesn't account for version 1.5 of the spec

will have a look at updating the AppImage tooling

**Comment by asensi** [comment]
Hello, I would suggest using `SingleMainWindow=true` instead of `SingleMainWindow=True`. That change avoids some errors like:

> I try to package the latest unstable ktorrent based on this commit, but there is a desktop-file-validate error from the check stage:
> 
> $ desktop-file-validate org.kde.ktorrent.desktop 
> org.kde.ktorrent.desktop: error: value "True" for boolean key "SingleMainWindow" in group "Desktop Entry" contains invalid characters, boolean values must be "false" or "true"
>      --  https://invent.kde.org/network/ktorrent/-/commit/95ec8bef250748f67b6cbb06abb944118b5aa9ac#note_488877

**Comment by mgallien** [comment]
closing in favor of https://github.com/nextcloud/desktop/pull/7124

**Pull request closed without merging**
