### PR TITLE
Fix MacOS UTF-8 normalization issue

### PR DESCRIPTION
**Pull request by xavi-b**
Fix https://github.com/nextcloud/desktop/issues/4950

### CODE REVIEW

**Review by claucambra — APPROVED** [review]
Thanks for the contribution!

This looks fine to me though why not implement this for all systems as a precautionary measure?

Would like to get your feedback before merging @mgallien @allexzander @camilasan

**Comment by mgallien** [comment]
@xavi-b thanks for your contribution

why do even need to use such a `phash` column with possibilities for troubles when we can just use the `path` column ?
I would rather remove the use for the `phash` column rather than trying to make it more robust just in case we can identify some of the problems of using it

**Review by claucambra — APPROVED** [review]
@mgallien Say we merge this for now, and get ride of hash down the road?

**Pull request merged**
