### PR TITLE
Use version of linuxdeploy-plugin-qt from PR in the project.

### PR DESCRIPTION
**Pull request by camilasan**
Fix for https://github.com/nextcloud/desktop/issues/7128.
See https://github.com/linuxdeploy/linuxdeploy-plugin-qt/pull/186.

### CODE REVIEW

**Review by claucambra — APPROVED** [review]

**Review by mgallien — CHANGES_REQUESTED** [review]
still failing with error message about missing `v8_context_snapshot.bin` file

**Review by mgallien — APPROVED** [review]

**Comment by SpookOz** [comment]
This might be a silly question, but will the PR version notify us about the update when the stable version is released?

**Comment by mgallien** [comment]
@SpookOz most probably not as you would be using daily update channel when running an AppImage from a PR
that would then not notify you about new stable releases

**Pull request merged**
