### PR TITLE
Remove outdated icons

### PR DESCRIPTION
**Pull request by jancborchardt**
I couldn’t find any references to these old icon files anymore, but could you confirm @camilasan @juliushaertl @jpnurmi? :slightly_smiling_face:

### CODE REVIEW

**Comment by jancborchardt** [comment]
Anyone up for review @nextcloud/desktop? :)

**Comment by camilasan** [comment]
Thanks @jancborchardt!

**Comment by jancborchardt** [comment]
@rullzer good catch, fixed it! :boom:

**Comment by jancborchardt** [comment]
@DominiqueFuchs thanks a lot for doing some cleanup! :)

**Pull request merged**
